# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mep Monthly Report
# TODO: top level description

# %% [markdown]
# ## Imports

import os
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_ext_custom.tasks import gather_doc
from ecoscope_workflows_core.tasks.results import gather_output_files

# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
)

# %%
# call the task


time_range = (
    set_time_range.handle_errors(task_instance_id="time_range")
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Create Monthly Report

# %%
# parameters

monthly_report_params = dict(
    logo_path=...,
)

# %%
# call the task


monthly_report = (
    gather_doc.handle_errors(task_instance_id="monthly_report")
    .partial(
        title="MEP Monthly Report",
        time_range=time_range,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename="mep_monthly_report",
        doc_widgets=[],
        **monthly_report_params,
    )
    .call()
)


# %% [markdown]
# ## Gather Output Files

# %%
# parameters

output_files_params = dict()

# %%
# call the task


output_files = (
    gather_output_files.handle_errors(task_instance_id="output_files")
    .partial(files=[monthly_report, monthly_report], **output_files_params)
    .call()
)
