# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪


from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_ext_custom.tasks import gather_doc
from ecoscope_workflows_core.tasks.results import gather_output_files

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    time_range = (
        set_time_range.validate()
        .handle_errors(task_instance_id="time_range")
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    monthly_report = (
        gather_doc.validate()
        .handle_errors(task_instance_id="monthly_report")
        .partial(
            title="MEP Monthly Report",
            time_range=time_range,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="mep_monthly_report",
            doc_widgets=[],
            **(params_dict.get("monthly_report") or {}),
        )
        .call()
    )

    output_files = (
        gather_output_files.validate()
        .handle_errors(task_instance_id="output_files")
        .partial(
            files=[monthly_report, monthly_report],
            **(params_dict.get("output_files") or {}),
        )
        .call()
    )

    return output_files
