
workflow_details:
  name: "Collar Voltage Workflow"
  description: "Collar Voltage workflow"
er_client_name:
  data_source:
    name: "mep"
time_range:
  since: "2024-05-01T00:00:00Z"
  until: "2025-05-31T23:59:59Z"
filter_time_range:
  since: "2025-05-20T00:00:00Z"
  until: "2025-05-31T23:59:59Z"
subject_obs:
  subject_group_name: "MEP_Elephants_Ecoscope_Mt_Elgon"
groupers:
  groupers: 
    - "extra__subject__name"
