workflow_details:
  description: MEP Collared elephant report
  name: mep_sample
groupers:
  groupers:
    - subject_name
configure_base_maps:
  base_maps:
    - url: >-
        https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}
      opacity: 1
      max_zoom: 20
    - url: >-
        https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}
      opacity: 0.1
      max_zoom: 20
er_client_name:
  data_source:
    name: ymep
gee_project_name:
  data_source:
    name: ecoscope_poc
retrieve_ldx_db:
  input_method:
    file_path: /Users/tevintemu/Desktop/Ecoscope/shapefiles/landDx.gpkg
custom_trajs_filter:
  min_length_meters: 0.001
  max_length_meters: 5000
  min_time_secs: 1
  max_time_secs: 21600
  min_speed_kmhr: 0.01
  max_speed_kmhr: 9
time_range:
  since: '2025-11-30T21:00:00.000Z'
  until: '2026-01-25T21:00:00.000Z'
subject_group_var:
  var: MEP_Elephants_Ecoscope_Tsavo
