# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Collared Elephant Report
# TODO: top level description

# %% [markdown]
# ## Imports

import os
from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.io import set_gee_connection
from ecoscope_workflows_core.tasks.io import set_er_connection
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_ext_mep.tasks import create_directory
from ecoscope_workflows_ext_mep.tasks import download_land_dx
from ecoscope_workflows_ext_mep.tasks import load_landdx_aoi
from ecoscope_workflows_ext_mep.tasks import split_gdf_by_column
from ecoscope_workflows_ext_mep.tasks import annotate_gdf_dict_with_geometry_type
from ecoscope_workflows_ext_mep.tasks import create_map_layers_from_annotated_dict
from ecoscope_workflows_ext_mep.tasks import get_subjects_info
from ecoscope_workflows_ext_ecoscope.tasks.transformation import normalize_column
from ecoscope_workflows_core.tasks.transformation import map_columns
from ecoscope_workflows_ext_mep.tasks import view_df
from ecoscope_workflows_core.tasks.groupby import split_groups
from ecoscope_workflows_ext_mep.tasks import download_profile_photo
from ecoscope_workflows_ext_mep.tasks import persist_subject_info
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events
from ecoscope_workflows_ext_ecoscope.tasks.io import get_subjectgroup_observations
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import process_relocations
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory,
)
from ecoscope_workflows_core.tasks.transformation import add_temporal_index
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_classification
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_elliptical_time_density,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import determine_season_windows
from ecoscope_workflows_ext_mep.tasks import create_seasonal_labels
from ecoscope_workflows_core.tasks.transformation import sort_values
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_color_map
from ecoscope_workflows_core.tasks.transformation import map_values_with_unit
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polyline_layer
from ecoscope_workflows_core.tasks.skip import any_is_empty_df
from ecoscope_workflows_core.tasks.skip import any_dependency_skipped
from ecoscope_workflows_ext_mep.tasks import create_view_state_from_gdf
from ecoscope_workflows_ext_mep.tasks import combine_map_layers
from ecoscope_workflows_ext_mep.tasks import zip_grouped_by_key
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap
from ecoscope_workflows_core.tasks.io import persist_text
from ecoscope_workflows_core.tasks.results import create_map_widget_single_view
from ecoscope_workflows_core.tasks.skip import never
from ecoscope_workflows_core.tasks.results import merge_widget_views
from ecoscope_workflows_ext_mep.tasks import calculate_etd_by_groups
from ecoscope_workflows_ext_mep.tasks import generate_mcp_gdf
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polygon_layer
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df
from ecoscope_workflows_ext_mep.tasks import generate_seasonal_nsd_plot
from ecoscope_workflows_ext_mep.tasks import generate_seasonal_speed_plot
from ecoscope_workflows_ext_mep.tasks import generate_seasonal_mcp_asymptote_plot

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.handle_errors(task_instance_id="workflow_details")
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Set Google Earth Engine Data Source

# %%
# parameters

gee_client_params = dict(
    data_source=...,
)

# %%
# call the task


gee_client = (
    set_gee_connection.handle_errors(task_instance_id="gee_client")
    .partial(**gee_client_params)
    .call()
)


# %% [markdown]
# ## Connect to Earth Ranger instance

# %%
# parameters

er_client_params = dict(
    data_source=...,
)

# %%
# call the task


er_client = (
    set_er_connection.handle_errors(task_instance_id="er_client")
    .partial(**er_client_params)
    .call()
)


# %% [markdown]
# ## Configure Base Map Layers

# %%
# parameters

configure_base_maps_params = dict(
    base_maps=...,
)

# %%
# call the task


configure_base_maps = (
    set_base_maps.handle_errors(task_instance_id="configure_base_maps")
    .partial(**configure_base_maps_params)
    .call()
)


# %% [markdown]
# ## Configure grouping strategy

# %%
# parameters

configure_grouping_strategy_params = dict(
    groupers=...,
)

# %%
# call the task


configure_grouping_strategy = (
    set_groupers.handle_errors(task_instance_id="configure_grouping_strategy")
    .partial(**configure_grouping_strategy_params)
    .call()
)


# %% [markdown]
# ## Define time range

# %%
# parameters

define_time_range_params = dict(
    since=...,
    until=...,
)

# %%
# call the task


define_time_range = (
    set_time_range.handle_errors(task_instance_id="define_time_range")
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **define_time_range_params)
    .call()
)


# %% [markdown]
# ## Create output directory

# %%
# parameters

create_output_dir_params = dict(
    path_name=...,
)

# %%
# call the task


create_output_dir = (
    create_directory.handle_errors(task_instance_id="create_output_dir")
    .partial(**create_output_dir_params)
    .call()
)


# %% [markdown]
# ## Retrieve and unpack landDX db

# %%
# parameters

retrieve_ldx_db_params = dict(
    overwrite_existing=...,
    unzip=...,
)

# %%
# call the task


retrieve_ldx_db = (
    download_land_dx.handle_errors(task_instance_id="retrieve_ldx_db")
    .partial(
        path=create_output_dir,
        url="https://maraelephant.maps.arcgis.com/sharing/rest/content/items/6da0c9bdd43d4dd0ac59a4f3cd73dcab/data",
        **retrieve_ldx_db_params,
    )
    .call()
)


# %% [markdown]
# ## Load AOI from landDX

# %%
# parameters

load_aoi_params = dict(
    aoi=...,
)

# %%
# call the task


load_aoi = (
    load_landdx_aoi.handle_errors(task_instance_id="load_aoi")
    .partial(map_path=retrieve_ldx_db, **load_aoi_params)
    .call()
)


# %% [markdown]
# ## split landDX layers by type

# %%
# parameters

split_landdx_by_type_params = dict()

# %%
# call the task


split_landdx_by_type = (
    split_gdf_by_column.handle_errors(task_instance_id="split_landdx_by_type")
    .partial(gdf=load_aoi, column="type", **split_landdx_by_type_params)
    .call()
)


# %% [markdown]
# ## Annotate geometry types

# %%
# parameters

annotate_geom_types_params = dict()

# %%
# call the task


annotate_geom_types = (
    annotate_gdf_dict_with_geometry_type.handle_errors(
        task_instance_id="annotate_geom_types"
    )
    .partial(gdf_dict=split_landdx_by_type, **annotate_geom_types_params)
    .call()
)


# %% [markdown]
# ## Style landDX map layers

# %%
# parameters

create_styled_ldx_layers_params = dict(
    style_config=...,
)

# %%
# call the task


create_styled_ldx_layers = (
    create_map_layers_from_annotated_dict.handle_errors(
        task_instance_id="create_styled_ldx_layers"
    )
    .partial(annotated_dict=annotate_geom_types, **create_styled_ldx_layers_params)
    .call()
)


# %% [markdown]
# ## Get subject dataframe

# %%
# parameters

subject_df_params = dict(
    bbox=...,
    subject_group_id=...,
    subject_group_name=...,
    name=...,
    updated_since=...,
    updated_until=...,
    tracks=...,
    ids=...,
    max_ids_per_request=...,
    raise_on_empty=...,
)

# %%
# call the task


subject_df = (
    get_subjects_info.handle_errors(task_instance_id="subject_df")
    .partial(client=er_client, include_inactive=True, **subject_df_params)
    .call()
)


# %% [markdown]
# ## Normalize additional subject info

# %%
# parameters

normalize_subject_info_params = dict()

# %%
# call the task


normalize_subject_info = (
    normalize_column.handle_errors(task_instance_id="normalize_subject_info")
    .partial(column="additional", df=subject_df, **normalize_subject_info_params)
    .call()
)


# %% [markdown]
# ## Rename subject columns

# %%
# parameters

rename_subject_cols_params = dict()

# %%
# call the task


rename_subject_cols = (
    map_columns.handle_errors(task_instance_id="rename_subject_cols")
    .partial(
        drop_columns=[
            "url",
            "image_url",
            "common_name",
            "content_type",
            "additional__external_id",
            "additional__tm_animal_id",
            "additional__external_name",
        ],
        retain_columns=[
            "id",
            "name",
            "hex",
            "additional__rgb",
            "additional__sex",
            "additional__Bio",
            "additional__DOB",
            "additional__notes",
            "additional__status",
            "additional__region",
            "additional__country",
            "additional__id_photo",
            "additional__distribution",
        ],
        rename_columns={
            "id": "groupby_col",
            "name": "subject_name",
            "hex": "hex_color",
        },
        df=normalize_subject_info,
        **rename_subject_cols_params,
    )
    .call()
)


# %% [markdown]
# ## view subject df

# %%
# parameters

view_subj_df_params = dict()

# %%
# call the task


view_subj_df = (
    view_df.handle_errors(task_instance_id="view_subj_df")
    .partial(name="Subject DataFrame", gdf=rename_subject_cols, **view_subj_df_params)
    .call()
)


# %% [markdown]
# ## split subjects df by group

# %%
# parameters

split_subject_by_group_params = dict()

# %%
# call the task


split_subject_by_group = (
    split_groups.handle_errors(task_instance_id="split_subject_by_group")
    .partial(
        df=rename_subject_cols,
        groupers=configure_grouping_strategy,
        **split_subject_by_group_params,
    )
    .call()
)


# %% [markdown]
# ## Download subject profile photo

# %%
# parameters

download_profile_pic_params = dict()

# %%
# call the task


download_profile_pic = (
    download_profile_photo.handle_errors(task_instance_id="download_profile_pic")
    .partial(
        image_type=".png",
        column="additional__id_photo",
        overwrite_existing=True,
        output_path=create_output_dir,
        **download_profile_pic_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_subject_by_group)
)


# %% [markdown]
# ## Download subject info and persist

# %%
# parameters

download_subject_info_params = dict(
    return_data=...,
)

# %%
# call the task


download_subject_info = (
    persist_subject_info.handle_errors(task_instance_id="download_subject_info")
    .partial(maxlen=1000, output_path=create_output_dir, **download_subject_info_params)
    .mapvalues(argnames=["df"], argvalues=split_subject_by_group)
)


# %% [markdown]
# ## Retrieve events from ER

# %%
# parameters

get_events_data_params = dict(
    event_types=...,
    include_null_geometry=...,
    include_updates=...,
    include_related_events=...,
)

# %%
# call the task


get_events_data = (
    get_events.handle_errors(task_instance_id="get_events_data")
    .partial(
        client=er_client,
        time_range=define_time_range,
        include_details=True,
        raise_on_empty=True,
        event_columns=[
            "id",
            "time",
            "event_type",
            "event_category",
            "reported_by",
            "serial_number",
            "geometry",
            "event_details",
        ],
        **get_events_data_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize event details

# %%
# parameters

normalize_event_details_params = dict()

# %%
# call the task


normalize_event_details = (
    normalize_column.handle_errors(task_instance_id="normalize_event_details")
    .partial(
        column="event_details", df=get_events_data, **normalize_event_details_params
    )
    .call()
)


# %% [markdown]
# ## view events df

# %%
# parameters

view_events_df_params = dict(
    name=...,
)

# %%
# call the task


view_events_df = (
    view_df.handle_errors(task_instance_id="view_events_df")
    .partial(gdf=normalize_event_details, **view_events_df_params)
    .call()
)


# %% [markdown]
# ## Rename event columns

# %%
# parameters

rename_event_cols_params = dict()

# %%
# call the task


rename_event_cols = (
    map_columns.handle_errors(task_instance_id="rename_event_cols")
    .partial(
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "id": "groupby_col",
            "name": "subject_name",
            "hex": "hex_color",
            "event_details__pic": "pic",
            "event_details__region": "region",
            "event_details__source": "source",
            "event_details__details": "details",
            "event_details__subject": "groupby_col",
            "event_details__source_id": "source_id",
            "event_details__subject_id": "subject_name",
            "event_details__collaring_type": "collaring_type",
            "event_details__collaring_reason": "collaring_reason",
            "event_details__collar_checked_by": "collar_checked_by",
        },
        df=normalize_event_details,
        **rename_event_cols_params,
    )
    .call()
)


# %% [markdown]
# ## split events by group

# %%
# parameters

split_events_by_group_params = dict()

# %%
# call the task


split_events_by_group = (
    split_groups.handle_errors(task_instance_id="split_events_by_group")
    .partial(
        df=rename_event_cols,
        groupers=configure_grouping_strategy,
        **split_events_by_group_params,
    )
    .call()
)


# %% [markdown]
# ## Get subject group observations from ER

# %%
# parameters

subject_observations_params = dict(
    subject_group_name=...,
)

# %%
# call the task


subject_observations = (
    get_subjectgroup_observations.handle_errors(task_instance_id="subject_observations")
    .partial(
        client=er_client,
        time_range=define_time_range,
        raise_on_empty=False,
        include_details=False,
        include_subjectsource_details=False,
        **subject_observations_params,
    )
    .call()
)


# %% [markdown]
# ## Transform observations to relocations

# %%
# parameters

subject_relocations_params = dict()

# %%
# call the task


subject_relocations = (
    process_relocations.handle_errors(task_instance_id="subject_relocations")
    .partial(
        observations=subject_observations,
        relocs_columns=[
            "fixtime",
            "geometry",
            "groupby_col",
            "junk_status",
            "extra__created_at",
            "extra__subject__sex",
            "extra__subject__hex",
            "extra__subject__name",
            "extra__subject__subject_subtype",
        ],
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **subject_relocations_params,
    )
    .call()
)


# %% [markdown]
# ## Rename reloc columns

# %%
# parameters

rename_reloc_cols_params = dict()

# %%
# call the task


rename_reloc_cols = (
    map_columns.handle_errors(task_instance_id="rename_reloc_cols")
    .partial(
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "extra__subject__name": "subject_name",
            "extra__subject__hex": "hex_color",
            "extra__subject__sex": "subject_sex",
            "extra__subject__subject_subtype": "subject_subtype",
            "extra__created_at": "created_at",
        },
        df=subject_observations,
        **rename_reloc_cols_params,
    )
    .call()
)


# %% [markdown]
# ## view reloc df

# %%
# parameters

view_reloc_df_params = dict()

# %%
# call the task


view_reloc_df = (
    view_df.handle_errors(task_instance_id="view_reloc_df")
    .partial(
        name="Subject Relocations DataFrame",
        gdf=rename_reloc_cols,
        **view_reloc_df_params,
    )
    .call()
)


# %% [markdown]
# ## Split relocations by group

# %%
# parameters

split_relocs_by_group_params = dict()

# %%
# call the task


split_relocs_by_group = (
    split_groups.handle_errors(task_instance_id="split_relocs_by_group")
    .partial(
        df=rename_reloc_cols,
        groupers=configure_grouping_strategy,
        **split_relocs_by_group_params,
    )
    .call()
)


# %% [markdown]
# ## Convert relocations to trajectories

# %%
# parameters

convert_to_trajectories_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


convert_to_trajectories = (
    relocations_to_trajectory.handle_errors(task_instance_id="convert_to_trajectories")
    .partial(relocations=rename_reloc_cols, **convert_to_trajectories_params)
    .call()
)


# %% [markdown]
# ## Add temporal index to trajectories

# %%
# parameters

add_temporal_index_to_traj_params = dict()

# %%
# call the task


add_temporal_index_to_traj = (
    add_temporal_index.handle_errors(task_instance_id="add_temporal_index_to_traj")
    .partial(
        df=convert_to_trajectories,
        time_col="segment_start",
        groupers=configure_grouping_strategy,
        cast_to_datetime=True,
        format="mixed",
        **add_temporal_index_to_traj_params,
    )
    .call()
)


# %% [markdown]
# ## Classify trajectories by speed

# %%
# parameters

classify_trajectory_speed_bins_params = dict()

# %%
# call the task


classify_trajectory_speed_bins = (
    apply_classification.handle_errors(
        task_instance_id="classify_trajectory_speed_bins"
    )
    .partial(
        df=add_temporal_index_to_traj,
        input_column_name="speed_kmhr",
        output_column_name="speed_bins",
        classification_options={"scheme": "equal_interval", "k": 6},
        label_options={"label_ranges": False, "label_decimals": 1},
        **classify_trajectory_speed_bins_params,
    )
    .call()
)


# %% [markdown]
# ## Generate seasonal home range etd

# %%
# parameters

generate_seasonal_etd_params = dict(
    auto_scale_or_custom_cell_size=...,
    max_speed_factor=...,
    expansion_factor=...,
)

# %%
# call the task


generate_seasonal_etd = (
    calculate_elliptical_time_density.handle_errors(
        task_instance_id="generate_seasonal_etd"
    )
    .partial(
        crs="ESRI:53042",
        percentiles=[50.0, 60.0, 70.0, 80.0, 90.0, 95.0, 99.0],
        nodata_value="nan",
        band_count=1,
        trajectory_gdf=classify_trajectory_speed_bins,
        **generate_seasonal_etd_params,
    )
    .call()
)


# %% [markdown]
# ## Rename trajectory columns

# %%
# parameters

rename_trajectory_cols_params = dict()

# %%
# call the task


rename_trajectory_cols = (
    map_columns.handle_errors(task_instance_id="rename_trajectory_cols")
    .partial(
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "extra__subject_name": "subject_name",
            "extra__hex_color": "hex_color",
            "extra__subject_sex": "subject_sex",
            "extra__subject_subtype": "subject_subtype",
        },
        df=classify_trajectory_speed_bins,
        **rename_trajectory_cols_params,
    )
    .call()
)


# %% [markdown]
# ## View trajectory data

# %%
# parameters

view_trajectory_data_params = dict()

# %%
# call the task


view_trajectory_data = (
    view_df.handle_errors(task_instance_id="view_trajectory_data")
    .partial(
        name="Subject Trajectory DataFrame",
        gdf=rename_trajectory_cols,
        **view_trajectory_data_params,
    )
    .call()
)


# %% [markdown]
# ## Determine seasonal windows

# %%
# parameters

determine_seasonal_windows_params = dict()

# %%
# call the task


determine_seasonal_windows = (
    determine_season_windows.handle_errors(
        task_instance_id="determine_seasonal_windows"
    )
    .partial(
        client=gee_client,
        roi=generate_seasonal_etd,
        time_range=define_time_range,
        **determine_seasonal_windows_params,
    )
    .call()
)


# %% [markdown]
# ## Generate seasonal column

# %%
# parameters

add_season_labels_params = dict()

# %%
# call the task


add_season_labels = (
    create_seasonal_labels.handle_errors(task_instance_id="add_season_labels")
    .partial(
        traj=rename_trajectory_cols,
        total_percentiles=determine_seasonal_windows,
        **add_season_labels_params,
    )
    .call()
)


# %% [markdown]
# ## View seasonal labels

# %%
# parameters

view_seasonal_labels_params = dict()

# %%
# call the task


view_seasonal_labels = (
    view_df.handle_errors(task_instance_id="view_seasonal_labels")
    .partial(
        name="Subject Trajectory DataFrame with Seasonal Labels",
        gdf=add_season_labels,
        **view_seasonal_labels_params,
    )
    .call()
)


# %% [markdown]
# ## Split trajectories by group

# %%
# parameters

split_trajs_by_group_params = dict()

# %%
# call the task


split_trajs_by_group = (
    split_groups.handle_errors(task_instance_id="split_trajs_by_group")
    .partial(
        df=add_season_labels,
        groupers=configure_grouping_strategy,
        **split_trajs_by_group_params,
    )
    .call()
)


# %% [markdown]
# ## Sort trajectories by speed bins

# %%
# parameters

sort_trajs_by_speed_params = dict(
    ascending=...,
)

# %%
# call the task


sort_trajs_by_speed = (
    sort_values.handle_errors(task_instance_id="sort_trajs_by_speed")
    .partial(column_name="speed_bins", na_position="last", **sort_trajs_by_speed_params)
    .mapvalues(argnames=["df"], argvalues=split_trajs_by_group)
)


# %% [markdown]
# ## Apply colormap to speedbins

# %%
# parameters

apply_speed_colormap_params = dict()

# %%
# call the task


apply_speed_colormap = (
    apply_color_map.handle_errors(task_instance_id="apply_speed_colormap")
    .partial(
        input_column_name="speed_bins",
        output_column_name="speed_bins_colormap",
        colormap=["#1a9850", "#91cf60", "#d9ef8b", "#fee08b", "#fc8d59", "#d73027"],
        **apply_speed_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=sort_trajs_by_speed)
)


# %% [markdown]
# ## Format speed bins for legend

# %%
# parameters

format_speed_bin_labels_params = dict()

# %%
# call the task


format_speed_bin_labels = (
    map_values_with_unit.handle_errors(task_instance_id="format_speed_bin_labels")
    .partial(
        input_column_name="speed_bins",
        output_column_name="speed_bins_formatted",
        original_unit="km/h",
        new_unit="km/h",
        decimal_places=1,
        **format_speed_bin_labels_params,
    )
    .mapvalues(argnames=["df"], argvalues=apply_speed_colormap)
)


# %% [markdown]
# ## Format speed values for display

# %%
# parameters

format_speed_values_params = dict()

# %%
# call the task


format_speed_values = (
    map_values_with_unit.handle_errors(task_instance_id="format_speed_values")
    .partial(
        input_column_name="speed_kmhr",
        output_column_name="speed_kmhr",
        original_unit="km/h",
        new_unit="km/h",
        decimal_places=1,
        **format_speed_values_params,
    )
    .mapvalues(argnames=["df"], argvalues=format_speed_bin_labels)
)


# %% [markdown]
# ## Generata speedmap layers

# %%
# parameters

generate_speedmap_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_speedmap_layers = (
    create_polyline_layer.handle_errors(task_instance_id="generate_speedmap_layers")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"color_column": "speed_bins_colormap"},
        legend={
            "label_column": "speed_bins_formatted",
            "color_column": "speed_bins_colormap",
        },
        tooltip_columns=[
            "subject_name",
            "subject_sex",
            "subject_subtype",
            "speed_kmhr",
            "speed_bins",
            "dist_meters",
        ],
        **generate_speedmap_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=format_speed_values)
)


# %% [markdown]
# ## Zoom speed trajectories by view state

# %%
# parameters

zoom_traj_view_params = dict(
    zoom_value=...,
)

# %%
# call the task


zoom_traj_view = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_traj_view")
    .partial(pitch=0, bearing=0, **zoom_traj_view_params)
    .mapvalues(argnames=["gdf"], argvalues=format_speed_values)
)


# %% [markdown]
# ## Combine landdx and speedmap layers

# %%
# parameters

combine_landdx_speed_layers_params = dict()

# %%
# call the task


combine_landdx_speed_layers = (
    combine_map_layers.handle_errors(task_instance_id="combine_landdx_speed_layers")
    .partial(
        static_layers=create_styled_ldx_layers, **combine_landdx_speed_layers_params
    )
    .mapvalues(argnames=["grouped_layers"], argvalues=generate_speedmap_layers)
)


# %% [markdown]
# ## Zip speed layers and zoom values

# %%
# parameters

speedvalues_view_zip_params = dict()

# %%
# call the task


speedvalues_view_zip = (
    zip_grouped_by_key.handle_errors(task_instance_id="speedvalues_view_zip")
    .partial(
        left=combine_landdx_speed_layers,
        right=zoom_traj_view,
        **speedvalues_view_zip_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Speedmap

# %%
# parameters

draw_speedmap_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_speedmap = (
    draw_ecomap.handle_errors(task_instance_id="draw_speedmap")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Speed Values(Km/h)"},
        static=False,
        title=None,
        max_zoom=20,
        **draw_speedmap_params,
    )
    .mapvalues(argnames=["geo_layers", "view_state"], argvalues=speedvalues_view_zip)
)


# %% [markdown]
# ## Persist Speed Ecomap HTML Paths

# %%
# parameters

persist_speed_ecomap_urls_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_speed_ecomap_urls = (
    persist_text.handle_errors(task_instance_id="persist_speed_ecomap_urls")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_speed_ecomap_urls_params,
    )
    .mapvalues(argnames=["text"], argvalues=draw_speedmap)
)


# %% [markdown]
# ## Create Speed Ecomap Widgets

# %%
# parameters

create_speed_ecomap_widgets_params = dict()

# %%
# call the task


create_speed_ecomap_widgets = (
    create_map_widget_single_view.handle_errors(
        task_instance_id="create_speed_ecomap_widgets"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Speedmap", **create_speed_ecomap_widgets_params)
    .map(argnames=["view", "data"], argvalues=persist_speed_ecomap_urls)
)


# %% [markdown]
# ## Merge Speed Ecomap Widgets

# %%
# parameters

merge_speed_ecomap_widgets_params = dict()

# %%
# call the task


merge_speed_ecomap_widgets = (
    merge_widget_views.handle_errors(task_instance_id="merge_speed_ecomap_widgets")
    .partial(widgets=create_speed_ecomap_widgets, **merge_speed_ecomap_widgets_params)
    .call()
)


# %% [markdown]
# ## Generate hr etd

# %%
# parameters

generate_etd_params = dict(
    auto_scale_or_custom_cell_size=...,
    max_speed_factor=...,
    expansion_factor=...,
)

# %%
# call the task


generate_etd = (
    calculate_etd_by_groups.handle_errors(task_instance_id="generate_etd")
    .partial(
        crs="ESRI:53042",
        percentiles=[50.0, 60.0, 70.0, 80.0, 90.0, 95.0, 99.0],
        nodata_value="nan",
        band_count=1,
        include_groups=True,
        groupby_cols=["season"],
        **generate_etd_params,
    )
    .mapvalues(argnames=["trajectory_gdf"], argvalues=split_trajs_by_group)
)


# %% [markdown]
# ## Generate MCP gdf

# %%
# parameters

calculate_mcp_params = dict()

# %%
# call the task


calculate_mcp = (
    generate_mcp_gdf.handle_errors(task_instance_id="calculate_mcp")
    .partial(planar_crs="ESRI:102022", **calculate_mcp_params)
    .mapvalues(argnames=["gdf"], argvalues=split_trajs_by_group)
)


# %% [markdown]
# ## Apply colormap to etd percentiles

# %%
# parameters

apply_etd_percentile_colormap_params = dict()

# %%
# call the task


apply_etd_percentile_colormap = (
    apply_color_map.handle_errors(task_instance_id="apply_etd_percentile_colormap")
    .partial(
        input_column_name="percentile",
        colormap="RdYlGn",
        output_column_name="percentile_colormap",
        **apply_etd_percentile_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=generate_etd)
)


# %% [markdown]
# ## Create hr etd layers

# %%
# parameters

generate_etd_ecomap_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_etd_ecomap_layers = (
    create_polygon_layer.handle_errors(task_instance_id="generate_etd_ecomap_layers")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"fill_color_column": "percentile_colormap", "opacity": 0.55},
        legend={"label_column": "percentile", "color_column": "percentile_colormap"},
        tooltip_columns=["percentile"],
        **generate_etd_ecomap_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=apply_etd_percentile_colormap)
)


# %% [markdown]
# ## Zoom hr movement by view state

# %%
# parameters

zoom_hr_view_params = dict(
    zoom_value=...,
)

# %%
# call the task


zoom_hr_view = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_hr_view")
    .partial(pitch=0, bearing=0, **zoom_hr_view_params)
    .mapvalues(argnames=["gdf"], argvalues=apply_etd_percentile_colormap)
)


# %% [markdown]
# ## Combine ldx and hr layers

# %%
# parameters

combine_landdx_hr_ecomap_layers_params = dict()

# %%
# call the task


combine_landdx_hr_ecomap_layers = (
    combine_map_layers.handle_errors(task_instance_id="combine_landdx_hr_ecomap_layers")
    .partial(
        static_layers=create_styled_ldx_layers, **combine_landdx_hr_ecomap_layers_params
    )
    .mapvalues(argnames=["grouped_layers"], argvalues=generate_etd_ecomap_layers)
)


# %% [markdown]
# ## Zip hr layers and zoom values

# %%
# parameters

hr_view_zip_params = dict()

# %%
# call the task


hr_view_zip = (
    zip_grouped_by_key.handle_errors(task_instance_id="hr_view_zip")
    .partial(
        left=combine_landdx_hr_ecomap_layers, right=zoom_hr_view, **hr_view_zip_params
    )
    .call()
)


# %% [markdown]
# ## Draw Home Range Ecomaps by Group

# %%
# parameters

draw_hr_ecomaps_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_hr_ecomaps = (
    draw_ecomap.handle_errors(task_instance_id="draw_hr_ecomaps")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Home Range Metrics"},
        static=False,
        title=None,
        max_zoom=20,
        **draw_hr_ecomaps_params,
    )
    .mapvalues(argnames=["geo_layers", "view_state"], argvalues=hr_view_zip)
)


# %% [markdown]
# ## Persist hr ecomap html urls

# %%
# parameters

persist_hr_ecomap_urls_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_hr_ecomap_urls = (
    persist_text.handle_errors(task_instance_id="persist_hr_ecomap_urls")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_hr_ecomap_urls_params,
    )
    .mapvalues(argnames=["text"], argvalues=draw_hr_ecomaps)
)


# %% [markdown]
# ## Create hr ecomap widgets

# %%
# parameters

create_hr_ecomap_widgets_params = dict()

# %%
# call the task


create_hr_ecomap_widgets = (
    create_map_widget_single_view.handle_errors(
        task_instance_id="create_hr_ecomap_widgets"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Home Range Ecomap", **create_hr_ecomap_widgets_params)
    .map(argnames=["view", "data"], argvalues=persist_hr_ecomap_urls)
)


# %% [markdown]
# ## Merge hr ecomap widgets

# %%
# parameters

merge_hr_ecomap_widgets_params = dict()

# %%
# call the task


merge_hr_ecomap_widgets = (
    merge_widget_views.handle_errors(task_instance_id="merge_hr_ecomap_widgets")
    .partial(widgets=create_hr_ecomap_widgets, **merge_hr_ecomap_widgets_params)
    .call()
)


# %% [markdown]
# ## time density colormap

# %%
# parameters

season_colormap_params = dict()

# %%
# call the task


season_colormap = (
    apply_color_map.handle_errors(task_instance_id="season_colormap")
    .partial(
        input_column_name="season",
        output_column_name="season_colormap",
        colormap=["#f57c00", "#4cf3f7"],
        **season_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=generate_etd)
)


# %% [markdown]
# ## Create season layers

# %%
# parameters

season_etd_map_layer_params = dict(
    zoom=...,
)

# %%
# call the task


season_etd_map_layer = (
    create_polygon_layer.handle_errors(task_instance_id="season_etd_map_layer")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"fill_color_column": "season_colormap", "opacity": 0.65},
        legend={"label_column": "season", "color_column": "season_colormap"},
        tooltip_columns=["percentile"],
        **season_etd_map_layer_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=season_colormap)
)


# %% [markdown]
# ## Create MCP Polygon Layer

# %%
# parameters

generate_mcp_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_mcp_layers = (
    create_polygon_layer.handle_errors(task_instance_id="generate_mcp_layers")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "get_fill_color": "#FFFFFF00",
            "get_line_color": "#dc143c",
            "opacity": 0.55,
            "stroked": True,
        },
        legend={"labels": ["mcp"], "colors": ["#dc143c"]},
        tooltip_columns=["area_km2"],
        **generate_mcp_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=calculate_mcp)
)


# %% [markdown]
# ## zip mcp and season hr

# %%
# parameters

zip_season_mcp_hr_params = dict()

# %%
# call the task


zip_season_mcp_hr = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_season_mcp_hr")
    .partial(
        left=generate_mcp_layers, right=season_etd_map_layer, **zip_season_mcp_hr_params
    )
    .call()
)


# %% [markdown]
# ## Zoom seasons by view state

# %%
# parameters

zoom_season_view_params = dict(
    zoom_value=...,
)

# %%
# call the task


zoom_season_view = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_season_view")
    .partial(pitch=0, bearing=0, **zoom_season_view_params)
    .mapvalues(argnames=["gdf"], argvalues=season_colormap)
)


# %% [markdown]
# ## Combine map layers

# %%
# parameters

comb_season_map_layers_params = dict()

# %%
# call the task


comb_season_map_layers = (
    combine_map_layers.handle_errors(task_instance_id="comb_season_map_layers")
    .partial(static_layers=create_styled_ldx_layers, **comb_season_map_layers_params)
    .mapvalues(argnames=["grouped_layers"], argvalues=zip_season_mcp_hr)
)


# %% [markdown]
# ## Zip seasons layers and zoom values

# %%
# parameters

seasons_view_zip_params = dict()

# %%
# call the task


seasons_view_zip = (
    zip_grouped_by_key.handle_errors(task_instance_id="seasons_view_zip")
    .partial(
        left=comb_season_map_layers, right=zoom_season_view, **seasons_view_zip_params
    )
    .call()
)


# %% [markdown]
# ## Draw Season Ecomap

# %%
# parameters

seasonal_ecomap_params = dict(
    widget_id=...,
)

# %%
# call the task


seasonal_ecomap = (
    draw_ecomap.handle_errors(task_instance_id="seasonal_ecomap")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Seasons"},
        static=False,
        title=None,
        max_zoom=20,
        **seasonal_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers", "view_state"], argvalues=seasons_view_zip)
)


# %% [markdown]
# ## Perist HR ecomap as text

# %%
# parameters

season_etd_ecomap_html_url_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


season_etd_ecomap_html_url = (
    persist_text.handle_errors(task_instance_id="season_etd_ecomap_html_url")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **season_etd_ecomap_html_url_params,
    )
    .mapvalues(argnames=["text"], argvalues=seasonal_ecomap)
)


# %% [markdown]
# ## Create Map Widgets for Trajectories

# %%
# parameters

season_etd_widgets_single_view_params = dict()

# %%
# call the task


season_etd_widgets_single_view = (
    create_map_widget_single_view.handle_errors(
        task_instance_id="season_etd_widgets_single_view"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Subject Group Home Range Map (Seasons)",
        **season_etd_widgets_single_view_params,
    )
    .map(argnames=["view", "data"], argvalues=season_etd_ecomap_html_url)
)


# %% [markdown]
# ## Merge Ecomap Widgets

# %%
# parameters

season_grouped_map_widget_params = dict()

# %%
# call the task


season_grouped_map_widget = (
    merge_widget_views.handle_errors(task_instance_id="season_grouped_map_widget")
    .partial(widgets=season_etd_widgets_single_view, **season_grouped_map_widget_params)
    .call()
)


# %% [markdown]
# ## Determine seasonal windows for each subject

# %%
# parameters

determine_subject_season_win_params = dict()

# %%
# call the task


determine_subject_season_win = (
    determine_season_windows.handle_errors(
        task_instance_id="determine_subject_season_win"
    )
    .partial(
        client=gee_client,
        time_range=define_time_range,
        **determine_subject_season_win_params,
    )
    .mapvalues(argnames=["roi"], argvalues=generate_etd)
)


# %% [markdown]
# ## Persist seasonal windows as csv

# %%
# parameters

persist_subject_season_wins_params = dict(
    filename=...,
    filetype=...,
)

# %%
# call the task


persist_subject_season_wins = (
    persist_df.handle_errors(task_instance_id="persist_subject_season_wins")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_subject_season_wins_params,
    )
    .mapvalues(argnames=["df"], argvalues=determine_subject_season_win)
)


# %% [markdown]
# ## Zip gdf and seasonal windows

# %%
# parameters

zip_nsd_values_params = dict()

# %%
# call the task


zip_nsd_values = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_nsd_values")
    .partial(
        left=split_relocs_by_group,
        right=persist_subject_season_wins,
        **zip_nsd_values_params,
    )
    .call()
)


# %% [markdown]
# ## Generate seasonal nsd plot

# %%
# parameters

generate_nsd_plot_params = dict(
    widget_id=...,
)

# %%
# call the task


generate_nsd_plot = (
    generate_seasonal_nsd_plot.handle_errors(task_instance_id="generate_nsd_plot")
    .partial(**generate_nsd_plot_params)
    .mapvalues(argnames=["gdf", "seasons_df"], argvalues=zip_nsd_values)
)


# %% [markdown]
# ## Persist seasonal nsd plots

# %%
# parameters

persist_seasonal_nsd_plots_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_seasonal_nsd_plots = (
    persist_text.handle_errors(task_instance_id="persist_seasonal_nsd_plots")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_seasonal_nsd_plots_params,
    )
    .mapvalues(argnames=["text"], argvalues=generate_nsd_plot)
)


# %% [markdown]
# ## zip gdf and seasonal windows for speed_plot

# %%
# parameters

zip_speed_values_params = dict()

# %%
# call the task


zip_speed_values = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_speed_values")
    .partial(
        left=split_relocs_by_group,
        right=persist_subject_season_wins,
        **zip_speed_values_params,
    )
    .call()
)


# %% [markdown]
# ## Generate seasonal speed plot

# %%
# parameters

generate_speed_plot_params = dict(
    widget_id=...,
)

# %%
# call the task


generate_speed_plot = (
    generate_seasonal_speed_plot.handle_errors(task_instance_id="generate_speed_plot")
    .partial(**generate_speed_plot_params)
    .mapvalues(argnames=["gdf", "seasons_df"], argvalues=zip_speed_values)
)


# %% [markdown]
# ## Persist seasonal speed plots

# %%
# parameters

persist_seasonal_speed_plots_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_seasonal_speed_plots = (
    persist_text.handle_errors(task_instance_id="persist_seasonal_speed_plots")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_seasonal_speed_plots_params,
    )
    .mapvalues(argnames=["text"], argvalues=generate_speed_plot)
)


# %% [markdown]
# ## Zip gdf for mcp asymptote plot

# %%
# parameters

zip_mcp_asymp_values_params = dict()

# %%
# call the task


zip_mcp_asymp_values = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_mcp_asymp_values")
    .partial(
        left=split_relocs_by_group,
        right=persist_subject_season_wins,
        **zip_mcp_asymp_values_params,
    )
    .call()
)


# %% [markdown]
# ## Generate mcp asymptote plot

# %%
# parameters

generate_mcp_asymp_plot_params = dict(
    widget_id=...,
)

# %%
# call the task


generate_mcp_asymp_plot = (
    generate_seasonal_mcp_asymptote_plot.handle_errors(
        task_instance_id="generate_mcp_asymp_plot"
    )
    .partial(**generate_mcp_asymp_plot_params)
    .mapvalues(argnames=["gdf", "seasons_df"], argvalues=zip_mcp_asymp_values)
)


# %% [markdown]
# ## Persist mcp asymptote plots

# %%
# parameters

persist_mcp_asymp_plots_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_mcp_asymp_plots = (
    persist_text.handle_errors(task_instance_id="persist_mcp_asymp_plots")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_mcp_asymp_plots_params,
    )
    .mapvalues(argnames=["text"], argvalues=generate_mcp_asymp_plot)
)
