# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, Graph, Node

from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.io import set_gee_connection
from ecoscope_workflows_core.tasks.io import set_er_connection
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_ext_mep.tasks import create_directory
from ecoscope_workflows_ext_mep.tasks import download_land_dx
from ecoscope_workflows_ext_mep.tasks import load_landdx_aoi
from ecoscope_workflows_ext_mep.tasks import split_gdf_by_column
from ecoscope_workflows_ext_mep.tasks import annotate_gdf_dict_with_geometry_type
from ecoscope_workflows_ext_mep.tasks import create_map_layers_from_annotated_dict
from ecoscope_workflows_ext_mep.tasks import get_subjects_info
from ecoscope_workflows_ext_ecoscope.tasks.transformation import normalize_column
from ecoscope_workflows_core.tasks.transformation import map_columns
from ecoscope_workflows_ext_mep.tasks import view_df
from ecoscope_workflows_core.tasks.groupby import split_groups
from ecoscope_workflows_ext_mep.tasks import download_profile_photo
from ecoscope_workflows_ext_mep.tasks import persist_subject_info
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events
from ecoscope_workflows_ext_ecoscope.tasks.io import get_subjectgroup_observations
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import process_relocations
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory,
)
from ecoscope_workflows_core.tasks.transformation import add_temporal_index
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_classification
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_elliptical_time_density,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import determine_season_windows
from ecoscope_workflows_ext_mep.tasks import create_seasonal_labels
from ecoscope_workflows_core.tasks.transformation import sort_values
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_color_map
from ecoscope_workflows_core.tasks.transformation import map_values_with_unit
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polyline_layer
from ecoscope_workflows_core.tasks.skip import any_is_empty_df
from ecoscope_workflows_core.tasks.skip import any_dependency_skipped
from ecoscope_workflows_ext_mep.tasks import create_view_state_from_gdf
from ecoscope_workflows_ext_mep.tasks import combine_map_layers
from ecoscope_workflows_ext_mep.tasks import zip_grouped_by_key
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap
from ecoscope_workflows_core.tasks.io import persist_text
from ecoscope_workflows_core.tasks.results import create_map_widget_single_view
from ecoscope_workflows_core.tasks.skip import never
from ecoscope_workflows_core.tasks.results import merge_widget_views
from ecoscope_workflows_ext_mep.tasks import calculate_etd_by_groups
from ecoscope_workflows_ext_mep.tasks import generate_mcp_gdf
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polygon_layer
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df
from ecoscope_workflows_ext_mep.tasks import generate_seasonal_nsd_plot
from ecoscope_workflows_ext_mep.tasks import generate_seasonal_speed_plot
from ecoscope_workflows_ext_mep.tasks import generate_seasonal_mcp_asymptote_plot

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "gee_client": [],
        "er_client": [],
        "configure_base_maps": [],
        "configure_grouping_strategy": [],
        "define_time_range": [],
        "create_output_dir": [],
        "retrieve_ldx_db": ["create_output_dir"],
        "load_aoi": ["retrieve_ldx_db"],
        "split_landdx_by_type": ["load_aoi"],
        "annotate_geom_types": ["split_landdx_by_type"],
        "create_styled_ldx_layers": ["annotate_geom_types"],
        "subject_df": ["er_client"],
        "normalize_subject_info": ["subject_df"],
        "rename_subject_cols": ["normalize_subject_info"],
        "view_subj_df": ["rename_subject_cols"],
        "split_subject_by_group": [
            "rename_subject_cols",
            "configure_grouping_strategy",
        ],
        "download_profile_pic": ["create_output_dir", "split_subject_by_group"],
        "download_subject_info": ["create_output_dir", "split_subject_by_group"],
        "get_events_data": ["er_client", "define_time_range"],
        "normalize_event_details": ["get_events_data"],
        "view_events_df": ["normalize_event_details"],
        "rename_event_cols": ["normalize_event_details"],
        "split_events_by_group": ["rename_event_cols", "configure_grouping_strategy"],
        "subject_observations": ["er_client", "define_time_range"],
        "subject_relocations": ["subject_observations"],
        "rename_reloc_cols": ["subject_observations"],
        "view_reloc_df": ["rename_reloc_cols"],
        "split_relocs_by_group": ["rename_reloc_cols", "configure_grouping_strategy"],
        "convert_to_trajectories": ["rename_reloc_cols"],
        "add_temporal_index_to_traj": [
            "convert_to_trajectories",
            "configure_grouping_strategy",
        ],
        "classify_trajectory_speed_bins": ["add_temporal_index_to_traj"],
        "generate_seasonal_etd": ["classify_trajectory_speed_bins"],
        "rename_trajectory_cols": ["classify_trajectory_speed_bins"],
        "view_trajectory_data": ["rename_trajectory_cols"],
        "determine_seasonal_windows": [
            "gee_client",
            "generate_seasonal_etd",
            "define_time_range",
        ],
        "add_season_labels": ["rename_trajectory_cols", "determine_seasonal_windows"],
        "view_seasonal_labels": ["add_season_labels"],
        "split_trajs_by_group": ["add_season_labels", "configure_grouping_strategy"],
        "sort_trajs_by_speed": ["split_trajs_by_group"],
        "apply_speed_colormap": ["sort_trajs_by_speed"],
        "format_speed_bin_labels": ["apply_speed_colormap"],
        "format_speed_values": ["format_speed_bin_labels"],
        "generate_speedmap_layers": ["format_speed_values"],
        "zoom_traj_view": ["format_speed_values"],
        "combine_landdx_speed_layers": [
            "create_styled_ldx_layers",
            "generate_speedmap_layers",
        ],
        "speedvalues_view_zip": ["combine_landdx_speed_layers", "zoom_traj_view"],
        "draw_speedmap": ["configure_base_maps", "speedvalues_view_zip"],
        "persist_speed_ecomap_urls": ["draw_speedmap"],
        "create_speed_ecomap_widgets": ["persist_speed_ecomap_urls"],
        "merge_speed_ecomap_widgets": ["create_speed_ecomap_widgets"],
        "generate_etd": ["split_trajs_by_group"],
        "calculate_mcp": ["split_trajs_by_group"],
        "apply_etd_percentile_colormap": ["generate_etd"],
        "generate_etd_ecomap_layers": ["apply_etd_percentile_colormap"],
        "zoom_hr_view": ["apply_etd_percentile_colormap"],
        "combine_landdx_hr_ecomap_layers": [
            "create_styled_ldx_layers",
            "generate_etd_ecomap_layers",
        ],
        "hr_view_zip": ["combine_landdx_hr_ecomap_layers", "zoom_hr_view"],
        "draw_hr_ecomaps": ["configure_base_maps", "hr_view_zip"],
        "persist_hr_ecomap_urls": ["draw_hr_ecomaps"],
        "create_hr_ecomap_widgets": ["persist_hr_ecomap_urls"],
        "merge_hr_ecomap_widgets": ["create_hr_ecomap_widgets"],
        "season_colormap": ["generate_etd"],
        "season_etd_map_layer": ["season_colormap"],
        "generate_mcp_layers": ["calculate_mcp"],
        "zip_season_mcp_hr": ["generate_mcp_layers", "season_etd_map_layer"],
        "zoom_season_view": ["season_colormap"],
        "comb_season_map_layers": ["create_styled_ldx_layers", "zip_season_mcp_hr"],
        "seasons_view_zip": ["comb_season_map_layers", "zoom_season_view"],
        "seasonal_ecomap": ["configure_base_maps", "seasons_view_zip"],
        "season_etd_ecomap_html_url": ["seasonal_ecomap"],
        "season_etd_widgets_single_view": ["season_etd_ecomap_html_url"],
        "season_grouped_map_widget": ["season_etd_widgets_single_view"],
        "determine_subject_season_win": [
            "gee_client",
            "define_time_range",
            "generate_etd",
        ],
        "persist_subject_season_wins": ["determine_subject_season_win"],
        "zip_nsd_values": ["split_relocs_by_group", "persist_subject_season_wins"],
        "generate_nsd_plot": ["zip_nsd_values"],
        "persist_seasonal_nsd_plots": ["generate_nsd_plot"],
        "zip_speed_values": ["split_relocs_by_group", "persist_subject_season_wins"],
        "generate_speed_plot": ["zip_speed_values"],
        "persist_seasonal_speed_plots": ["generate_speed_plot"],
        "zip_mcp_asymp_values": [
            "split_relocs_by_group",
            "persist_subject_season_wins",
        ],
        "generate_mcp_asymp_plot": ["zip_mcp_asymp_values"],
        "persist_mcp_asymp_plots": ["generate_mcp_asymp_plot"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .handle_errors(task_instance_id="workflow_details")
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "gee_client": Node(
            async_task=set_gee_connection.validate()
            .handle_errors(task_instance_id="gee_client")
            .set_executor("lithops"),
            partial=(params_dict.get("gee_client") or {}),
            method="call",
        ),
        "er_client": Node(
            async_task=set_er_connection.validate()
            .handle_errors(task_instance_id="er_client")
            .set_executor("lithops"),
            partial=(params_dict.get("er_client") or {}),
            method="call",
        ),
        "configure_base_maps": Node(
            async_task=set_base_maps.validate()
            .handle_errors(task_instance_id="configure_base_maps")
            .set_executor("lithops"),
            partial=(params_dict.get("configure_base_maps") or {}),
            method="call",
        ),
        "configure_grouping_strategy": Node(
            async_task=set_groupers.validate()
            .handle_errors(task_instance_id="configure_grouping_strategy")
            .set_executor("lithops"),
            partial=(params_dict.get("configure_grouping_strategy") or {}),
            method="call",
        ),
        "define_time_range": Node(
            async_task=set_time_range.validate()
            .handle_errors(task_instance_id="define_time_range")
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("define_time_range") or {}),
            method="call",
        ),
        "create_output_dir": Node(
            async_task=create_directory.validate()
            .handle_errors(task_instance_id="create_output_dir")
            .set_executor("lithops"),
            partial=(params_dict.get("create_output_dir") or {}),
            method="call",
        ),
        "retrieve_ldx_db": Node(
            async_task=download_land_dx.validate()
            .handle_errors(task_instance_id="retrieve_ldx_db")
            .set_executor("lithops"),
            partial={
                "path": DependsOn("create_output_dir"),
                "url": "https://maraelephant.maps.arcgis.com/sharing/rest/content/items/6da0c9bdd43d4dd0ac59a4f3cd73dcab/data",
            }
            | (params_dict.get("retrieve_ldx_db") or {}),
            method="call",
        ),
        "load_aoi": Node(
            async_task=load_landdx_aoi.validate()
            .handle_errors(task_instance_id="load_aoi")
            .set_executor("lithops"),
            partial={
                "map_path": DependsOn("retrieve_ldx_db"),
            }
            | (params_dict.get("load_aoi") or {}),
            method="call",
        ),
        "split_landdx_by_type": Node(
            async_task=split_gdf_by_column.validate()
            .handle_errors(task_instance_id="split_landdx_by_type")
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("load_aoi"),
                "column": "type",
            }
            | (params_dict.get("split_landdx_by_type") or {}),
            method="call",
        ),
        "annotate_geom_types": Node(
            async_task=annotate_gdf_dict_with_geometry_type.validate()
            .handle_errors(task_instance_id="annotate_geom_types")
            .set_executor("lithops"),
            partial={
                "gdf_dict": DependsOn("split_landdx_by_type"),
            }
            | (params_dict.get("annotate_geom_types") or {}),
            method="call",
        ),
        "create_styled_ldx_layers": Node(
            async_task=create_map_layers_from_annotated_dict.validate()
            .handle_errors(task_instance_id="create_styled_ldx_layers")
            .set_executor("lithops"),
            partial={
                "annotated_dict": DependsOn("annotate_geom_types"),
            }
            | (params_dict.get("create_styled_ldx_layers") or {}),
            method="call",
        ),
        "subject_df": Node(
            async_task=get_subjects_info.validate()
            .handle_errors(task_instance_id="subject_df")
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
                "include_inactive": True,
            }
            | (params_dict.get("subject_df") or {}),
            method="call",
        ),
        "normalize_subject_info": Node(
            async_task=normalize_column.validate()
            .handle_errors(task_instance_id="normalize_subject_info")
            .set_executor("lithops"),
            partial={
                "column": "additional",
                "df": DependsOn("subject_df"),
            }
            | (params_dict.get("normalize_subject_info") or {}),
            method="call",
        ),
        "rename_subject_cols": Node(
            async_task=map_columns.validate()
            .handle_errors(task_instance_id="rename_subject_cols")
            .set_executor("lithops"),
            partial={
                "drop_columns": [
                    "url",
                    "image_url",
                    "common_name",
                    "content_type",
                    "additional__external_id",
                    "additional__tm_animal_id",
                    "additional__external_name",
                ],
                "retain_columns": [
                    "id",
                    "name",
                    "hex",
                    "additional__rgb",
                    "additional__sex",
                    "additional__Bio",
                    "additional__DOB",
                    "additional__notes",
                    "additional__status",
                    "additional__region",
                    "additional__country",
                    "additional__id_photo",
                    "additional__distribution",
                ],
                "rename_columns": {
                    "id": "groupby_col",
                    "name": "subject_name",
                    "hex": "hex_color",
                },
                "df": DependsOn("normalize_subject_info"),
            }
            | (params_dict.get("rename_subject_cols") or {}),
            method="call",
        ),
        "view_subj_df": Node(
            async_task=view_df.validate()
            .handle_errors(task_instance_id="view_subj_df")
            .set_executor("lithops"),
            partial={
                "name": "Subject DataFrame",
                "gdf": DependsOn("rename_subject_cols"),
            }
            | (params_dict.get("view_subj_df") or {}),
            method="call",
        ),
        "split_subject_by_group": Node(
            async_task=split_groups.validate()
            .handle_errors(task_instance_id="split_subject_by_group")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_subject_cols"),
                "groupers": DependsOn("configure_grouping_strategy"),
            }
            | (params_dict.get("split_subject_by_group") or {}),
            method="call",
        ),
        "download_profile_pic": Node(
            async_task=download_profile_photo.validate()
            .handle_errors(task_instance_id="download_profile_pic")
            .set_executor("lithops"),
            partial={
                "image_type": ".png",
                "column": "additional__id_photo",
                "overwrite_existing": True,
                "output_path": DependsOn("create_output_dir"),
            }
            | (params_dict.get("download_profile_pic") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_by_group"),
            },
        ),
        "download_subject_info": Node(
            async_task=persist_subject_info.validate()
            .handle_errors(task_instance_id="download_subject_info")
            .set_executor("lithops"),
            partial={
                "maxlen": 1000,
                "output_path": DependsOn("create_output_dir"),
            }
            | (params_dict.get("download_subject_info") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_by_group"),
            },
        ),
        "get_events_data": Node(
            async_task=get_events.validate()
            .handle_errors(task_instance_id="get_events_data")
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
                "time_range": DependsOn("define_time_range"),
                "include_details": True,
                "raise_on_empty": True,
                "event_columns": [
                    "id",
                    "time",
                    "event_type",
                    "event_category",
                    "reported_by",
                    "serial_number",
                    "geometry",
                    "event_details",
                ],
            }
            | (params_dict.get("get_events_data") or {}),
            method="call",
        ),
        "normalize_event_details": Node(
            async_task=normalize_column.validate()
            .handle_errors(task_instance_id="normalize_event_details")
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("get_events_data"),
            }
            | (params_dict.get("normalize_event_details") or {}),
            method="call",
        ),
        "view_events_df": Node(
            async_task=view_df.validate()
            .handle_errors(task_instance_id="view_events_df")
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("normalize_event_details"),
            }
            | (params_dict.get("view_events_df") or {}),
            method="call",
        ),
        "rename_event_cols": Node(
            async_task=map_columns.validate()
            .handle_errors(task_instance_id="rename_event_cols")
            .set_executor("lithops"),
            partial={
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {
                    "id": "groupby_col",
                    "name": "subject_name",
                    "hex": "hex_color",
                    "event_details__pic": "pic",
                    "event_details__region": "region",
                    "event_details__source": "source",
                    "event_details__details": "details",
                    "event_details__subject": "groupby_col",
                    "event_details__source_id": "source_id",
                    "event_details__subject_id": "subject_name",
                    "event_details__collaring_type": "collaring_type",
                    "event_details__collaring_reason": "collaring_reason",
                    "event_details__collar_checked_by": "collar_checked_by",
                },
                "df": DependsOn("normalize_event_details"),
            }
            | (params_dict.get("rename_event_cols") or {}),
            method="call",
        ),
        "split_events_by_group": Node(
            async_task=split_groups.validate()
            .handle_errors(task_instance_id="split_events_by_group")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_event_cols"),
                "groupers": DependsOn("configure_grouping_strategy"),
            }
            | (params_dict.get("split_events_by_group") or {}),
            method="call",
        ),
        "subject_observations": Node(
            async_task=get_subjectgroup_observations.validate()
            .handle_errors(task_instance_id="subject_observations")
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
                "time_range": DependsOn("define_time_range"),
                "raise_on_empty": False,
                "include_details": False,
                "include_subjectsource_details": False,
            }
            | (params_dict.get("subject_observations") or {}),
            method="call",
        ),
        "subject_relocations": Node(
            async_task=process_relocations.validate()
            .handle_errors(task_instance_id="subject_relocations")
            .set_executor("lithops"),
            partial={
                "observations": DependsOn("subject_observations"),
                "relocs_columns": [
                    "fixtime",
                    "geometry",
                    "groupby_col",
                    "junk_status",
                    "extra__created_at",
                    "extra__subject__sex",
                    "extra__subject__hex",
                    "extra__subject__name",
                    "extra__subject__subject_subtype",
                ],
                "filter_point_coords": [
                    {"x": 180.0, "y": 90.0},
                    {"x": 0.0, "y": 0.0},
                    {"x": 1.0, "y": 1.0},
                ],
            }
            | (params_dict.get("subject_relocations") or {}),
            method="call",
        ),
        "rename_reloc_cols": Node(
            async_task=map_columns.validate()
            .handle_errors(task_instance_id="rename_reloc_cols")
            .set_executor("lithops"),
            partial={
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {
                    "extra__subject__name": "subject_name",
                    "extra__subject__hex": "hex_color",
                    "extra__subject__sex": "subject_sex",
                    "extra__subject__subject_subtype": "subject_subtype",
                    "extra__created_at": "created_at",
                },
                "df": DependsOn("subject_observations"),
            }
            | (params_dict.get("rename_reloc_cols") or {}),
            method="call",
        ),
        "view_reloc_df": Node(
            async_task=view_df.validate()
            .handle_errors(task_instance_id="view_reloc_df")
            .set_executor("lithops"),
            partial={
                "name": "Subject Relocations DataFrame",
                "gdf": DependsOn("rename_reloc_cols"),
            }
            | (params_dict.get("view_reloc_df") or {}),
            method="call",
        ),
        "split_relocs_by_group": Node(
            async_task=split_groups.validate()
            .handle_errors(task_instance_id="split_relocs_by_group")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_reloc_cols"),
                "groupers": DependsOn("configure_grouping_strategy"),
            }
            | (params_dict.get("split_relocs_by_group") or {}),
            method="call",
        ),
        "convert_to_trajectories": Node(
            async_task=relocations_to_trajectory.validate()
            .handle_errors(task_instance_id="convert_to_trajectories")
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("rename_reloc_cols"),
            }
            | (params_dict.get("convert_to_trajectories") or {}),
            method="call",
        ),
        "add_temporal_index_to_traj": Node(
            async_task=add_temporal_index.validate()
            .handle_errors(task_instance_id="add_temporal_index_to_traj")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_to_trajectories"),
                "time_col": "segment_start",
                "groupers": DependsOn("configure_grouping_strategy"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("add_temporal_index_to_traj") or {}),
            method="call",
        ),
        "classify_trajectory_speed_bins": Node(
            async_task=apply_classification.validate()
            .handle_errors(task_instance_id="classify_trajectory_speed_bins")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_temporal_index_to_traj"),
                "input_column_name": "speed_kmhr",
                "output_column_name": "speed_bins",
                "classification_options": {"scheme": "equal_interval", "k": 6},
                "label_options": {"label_ranges": False, "label_decimals": 1},
            }
            | (params_dict.get("classify_trajectory_speed_bins") or {}),
            method="call",
        ),
        "generate_seasonal_etd": Node(
            async_task=calculate_elliptical_time_density.validate()
            .handle_errors(task_instance_id="generate_seasonal_etd")
            .set_executor("lithops"),
            partial={
                "crs": "ESRI:53042",
                "percentiles": [50.0, 60.0, 70.0, 80.0, 90.0, 95.0, 99.0],
                "nodata_value": "nan",
                "band_count": 1,
                "trajectory_gdf": DependsOn("classify_trajectory_speed_bins"),
            }
            | (params_dict.get("generate_seasonal_etd") or {}),
            method="call",
        ),
        "rename_trajectory_cols": Node(
            async_task=map_columns.validate()
            .handle_errors(task_instance_id="rename_trajectory_cols")
            .set_executor("lithops"),
            partial={
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {
                    "extra__subject_name": "subject_name",
                    "extra__hex_color": "hex_color",
                    "extra__subject_sex": "subject_sex",
                    "extra__subject_subtype": "subject_subtype",
                },
                "df": DependsOn("classify_trajectory_speed_bins"),
            }
            | (params_dict.get("rename_trajectory_cols") or {}),
            method="call",
        ),
        "view_trajectory_data": Node(
            async_task=view_df.validate()
            .handle_errors(task_instance_id="view_trajectory_data")
            .set_executor("lithops"),
            partial={
                "name": "Subject Trajectory DataFrame",
                "gdf": DependsOn("rename_trajectory_cols"),
            }
            | (params_dict.get("view_trajectory_data") or {}),
            method="call",
        ),
        "determine_seasonal_windows": Node(
            async_task=determine_season_windows.validate()
            .handle_errors(task_instance_id="determine_seasonal_windows")
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_client"),
                "roi": DependsOn("generate_seasonal_etd"),
                "time_range": DependsOn("define_time_range"),
            }
            | (params_dict.get("determine_seasonal_windows") or {}),
            method="call",
        ),
        "add_season_labels": Node(
            async_task=create_seasonal_labels.validate()
            .handle_errors(task_instance_id="add_season_labels")
            .set_executor("lithops"),
            partial={
                "traj": DependsOn("rename_trajectory_cols"),
                "total_percentiles": DependsOn("determine_seasonal_windows"),
            }
            | (params_dict.get("add_season_labels") or {}),
            method="call",
        ),
        "view_seasonal_labels": Node(
            async_task=view_df.validate()
            .handle_errors(task_instance_id="view_seasonal_labels")
            .set_executor("lithops"),
            partial={
                "name": "Subject Trajectory DataFrame with Seasonal Labels",
                "gdf": DependsOn("add_season_labels"),
            }
            | (params_dict.get("view_seasonal_labels") or {}),
            method="call",
        ),
        "split_trajs_by_group": Node(
            async_task=split_groups.validate()
            .handle_errors(task_instance_id="split_trajs_by_group")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_season_labels"),
                "groupers": DependsOn("configure_grouping_strategy"),
            }
            | (params_dict.get("split_trajs_by_group") or {}),
            method="call",
        ),
        "sort_trajs_by_speed": Node(
            async_task=sort_values.validate()
            .handle_errors(task_instance_id="sort_trajs_by_speed")
            .set_executor("lithops"),
            partial={
                "column_name": "speed_bins",
                "na_position": "last",
            }
            | (params_dict.get("sort_trajs_by_speed") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_trajs_by_group"),
            },
        ),
        "apply_speed_colormap": Node(
            async_task=apply_color_map.validate()
            .handle_errors(task_instance_id="apply_speed_colormap")
            .set_executor("lithops"),
            partial={
                "input_column_name": "speed_bins",
                "output_column_name": "speed_bins_colormap",
                "colormap": [
                    "#1a9850",
                    "#91cf60",
                    "#d9ef8b",
                    "#fee08b",
                    "#fc8d59",
                    "#d73027",
                ],
            }
            | (params_dict.get("apply_speed_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("sort_trajs_by_speed"),
            },
        ),
        "format_speed_bin_labels": Node(
            async_task=map_values_with_unit.validate()
            .handle_errors(task_instance_id="format_speed_bin_labels")
            .set_executor("lithops"),
            partial={
                "input_column_name": "speed_bins",
                "output_column_name": "speed_bins_formatted",
                "original_unit": "km/h",
                "new_unit": "km/h",
                "decimal_places": 1,
            }
            | (params_dict.get("format_speed_bin_labels") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("apply_speed_colormap"),
            },
        ),
        "format_speed_values": Node(
            async_task=map_values_with_unit.validate()
            .handle_errors(task_instance_id="format_speed_values")
            .set_executor("lithops"),
            partial={
                "input_column_name": "speed_kmhr",
                "output_column_name": "speed_kmhr",
                "original_unit": "km/h",
                "new_unit": "km/h",
                "decimal_places": 1,
            }
            | (params_dict.get("format_speed_values") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("format_speed_bin_labels"),
            },
        ),
        "generate_speedmap_layers": Node(
            async_task=create_polyline_layer.validate()
            .handle_errors(task_instance_id="generate_speedmap_layers")
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {"color_column": "speed_bins_colormap"},
                "legend": {
                    "label_column": "speed_bins_formatted",
                    "color_column": "speed_bins_colormap",
                },
                "tooltip_columns": [
                    "subject_name",
                    "subject_sex",
                    "subject_subtype",
                    "speed_kmhr",
                    "speed_bins",
                    "dist_meters",
                ],
            }
            | (params_dict.get("generate_speedmap_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("format_speed_values"),
            },
        ),
        "zoom_traj_view": Node(
            async_task=create_view_state_from_gdf.validate()
            .handle_errors(task_instance_id="zoom_traj_view")
            .set_executor("lithops"),
            partial={
                "pitch": 0,
                "bearing": 0,
            }
            | (params_dict.get("zoom_traj_view") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("format_speed_values"),
            },
        ),
        "combine_landdx_speed_layers": Node(
            async_task=combine_map_layers.validate()
            .handle_errors(task_instance_id="combine_landdx_speed_layers")
            .set_executor("lithops"),
            partial={
                "static_layers": DependsOn("create_styled_ldx_layers"),
            }
            | (params_dict.get("combine_landdx_speed_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["grouped_layers"],
                "argvalues": DependsOn("generate_speedmap_layers"),
            },
        ),
        "speedvalues_view_zip": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="speedvalues_view_zip")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("combine_landdx_speed_layers"),
                "right": DependsOn("zoom_traj_view"),
            }
            | (params_dict.get("speedvalues_view_zip") or {}),
            method="call",
        ),
        "draw_speedmap": Node(
            async_task=draw_ecomap.validate()
            .handle_errors(task_instance_id="draw_speedmap")
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "north_arrow_style": {"placement": "top-left"},
                "legend_style": {
                    "placement": "bottom-right",
                    "title": "Speed Values(Km/h)",
                },
                "static": False,
                "title": None,
                "max_zoom": 20,
            }
            | (params_dict.get("draw_speedmap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers", "view_state"],
                "argvalues": DependsOn("speedvalues_view_zip"),
            },
        ),
        "persist_speed_ecomap_urls": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_speed_ecomap_urls")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_speed_ecomap_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("draw_speedmap"),
            },
        ),
        "create_speed_ecomap_widgets": Node(
            async_task=create_map_widget_single_view.validate()
            .handle_errors(task_instance_id="create_speed_ecomap_widgets")
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Speedmap",
            }
            | (params_dict.get("create_speed_ecomap_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_speed_ecomap_urls"),
            },
        ),
        "merge_speed_ecomap_widgets": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="merge_speed_ecomap_widgets")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("create_speed_ecomap_widgets"),
            }
            | (params_dict.get("merge_speed_ecomap_widgets") or {}),
            method="call",
        ),
        "generate_etd": Node(
            async_task=calculate_etd_by_groups.validate()
            .handle_errors(task_instance_id="generate_etd")
            .set_executor("lithops"),
            partial={
                "crs": "ESRI:53042",
                "percentiles": [50.0, 60.0, 70.0, 80.0, 90.0, 95.0, 99.0],
                "nodata_value": "nan",
                "band_count": 1,
                "include_groups": True,
                "groupby_cols": ["season"],
            }
            | (params_dict.get("generate_etd") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["trajectory_gdf"],
                "argvalues": DependsOn("split_trajs_by_group"),
            },
        ),
        "calculate_mcp": Node(
            async_task=generate_mcp_gdf.validate()
            .handle_errors(task_instance_id="calculate_mcp")
            .set_executor("lithops"),
            partial={
                "planar_crs": "ESRI:102022",
            }
            | (params_dict.get("calculate_mcp") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("split_trajs_by_group"),
            },
        ),
        "apply_etd_percentile_colormap": Node(
            async_task=apply_color_map.validate()
            .handle_errors(task_instance_id="apply_etd_percentile_colormap")
            .set_executor("lithops"),
            partial={
                "input_column_name": "percentile",
                "colormap": "RdYlGn",
                "output_column_name": "percentile_colormap",
            }
            | (params_dict.get("apply_etd_percentile_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("generate_etd"),
            },
        ),
        "generate_etd_ecomap_layers": Node(
            async_task=create_polygon_layer.validate()
            .handle_errors(task_instance_id="generate_etd_ecomap_layers")
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "fill_color_column": "percentile_colormap",
                    "opacity": 0.55,
                },
                "legend": {
                    "label_column": "percentile",
                    "color_column": "percentile_colormap",
                },
                "tooltip_columns": ["percentile"],
            }
            | (params_dict.get("generate_etd_ecomap_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("apply_etd_percentile_colormap"),
            },
        ),
        "zoom_hr_view": Node(
            async_task=create_view_state_from_gdf.validate()
            .handle_errors(task_instance_id="zoom_hr_view")
            .set_executor("lithops"),
            partial={
                "pitch": 0,
                "bearing": 0,
            }
            | (params_dict.get("zoom_hr_view") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("apply_etd_percentile_colormap"),
            },
        ),
        "combine_landdx_hr_ecomap_layers": Node(
            async_task=combine_map_layers.validate()
            .handle_errors(task_instance_id="combine_landdx_hr_ecomap_layers")
            .set_executor("lithops"),
            partial={
                "static_layers": DependsOn("create_styled_ldx_layers"),
            }
            | (params_dict.get("combine_landdx_hr_ecomap_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["grouped_layers"],
                "argvalues": DependsOn("generate_etd_ecomap_layers"),
            },
        ),
        "hr_view_zip": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="hr_view_zip")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("combine_landdx_hr_ecomap_layers"),
                "right": DependsOn("zoom_hr_view"),
            }
            | (params_dict.get("hr_view_zip") or {}),
            method="call",
        ),
        "draw_hr_ecomaps": Node(
            async_task=draw_ecomap.validate()
            .handle_errors(task_instance_id="draw_hr_ecomaps")
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "north_arrow_style": {"placement": "top-left"},
                "legend_style": {
                    "placement": "bottom-right",
                    "title": "Home Range Metrics",
                },
                "static": False,
                "title": None,
                "max_zoom": 20,
            }
            | (params_dict.get("draw_hr_ecomaps") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers", "view_state"],
                "argvalues": DependsOn("hr_view_zip"),
            },
        ),
        "persist_hr_ecomap_urls": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_hr_ecomap_urls")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_hr_ecomap_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("draw_hr_ecomaps"),
            },
        ),
        "create_hr_ecomap_widgets": Node(
            async_task=create_map_widget_single_view.validate()
            .handle_errors(task_instance_id="create_hr_ecomap_widgets")
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Home Range Ecomap",
            }
            | (params_dict.get("create_hr_ecomap_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_hr_ecomap_urls"),
            },
        ),
        "merge_hr_ecomap_widgets": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="merge_hr_ecomap_widgets")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("create_hr_ecomap_widgets"),
            }
            | (params_dict.get("merge_hr_ecomap_widgets") or {}),
            method="call",
        ),
        "season_colormap": Node(
            async_task=apply_color_map.validate()
            .handle_errors(task_instance_id="season_colormap")
            .set_executor("lithops"),
            partial={
                "input_column_name": "season",
                "output_column_name": "season_colormap",
                "colormap": ["#f57c00", "#4cf3f7"],
            }
            | (params_dict.get("season_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("generate_etd"),
            },
        ),
        "season_etd_map_layer": Node(
            async_task=create_polygon_layer.validate()
            .handle_errors(task_instance_id="season_etd_map_layer")
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "fill_color_column": "season_colormap",
                    "opacity": 0.65,
                },
                "legend": {"label_column": "season", "color_column": "season_colormap"},
                "tooltip_columns": ["percentile"],
            }
            | (params_dict.get("season_etd_map_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("season_colormap"),
            },
        ),
        "generate_mcp_layers": Node(
            async_task=create_polygon_layer.validate()
            .handle_errors(task_instance_id="generate_mcp_layers")
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "get_fill_color": "#FFFFFF00",
                    "get_line_color": "#dc143c",
                    "opacity": 0.55,
                    "stroked": True,
                },
                "legend": {"labels": ["mcp"], "colors": ["#dc143c"]},
                "tooltip_columns": ["area_km2"],
            }
            | (params_dict.get("generate_mcp_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("calculate_mcp"),
            },
        ),
        "zip_season_mcp_hr": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="zip_season_mcp_hr")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("generate_mcp_layers"),
                "right": DependsOn("season_etd_map_layer"),
            }
            | (params_dict.get("zip_season_mcp_hr") or {}),
            method="call",
        ),
        "zoom_season_view": Node(
            async_task=create_view_state_from_gdf.validate()
            .handle_errors(task_instance_id="zoom_season_view")
            .set_executor("lithops"),
            partial={
                "pitch": 0,
                "bearing": 0,
            }
            | (params_dict.get("zoom_season_view") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("season_colormap"),
            },
        ),
        "comb_season_map_layers": Node(
            async_task=combine_map_layers.validate()
            .handle_errors(task_instance_id="comb_season_map_layers")
            .set_executor("lithops"),
            partial={
                "static_layers": DependsOn("create_styled_ldx_layers"),
            }
            | (params_dict.get("comb_season_map_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["grouped_layers"],
                "argvalues": DependsOn("zip_season_mcp_hr"),
            },
        ),
        "seasons_view_zip": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="seasons_view_zip")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("comb_season_map_layers"),
                "right": DependsOn("zoom_season_view"),
            }
            | (params_dict.get("seasons_view_zip") or {}),
            method="call",
        ),
        "seasonal_ecomap": Node(
            async_task=draw_ecomap.validate()
            .handle_errors(task_instance_id="seasonal_ecomap")
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("configure_base_maps"),
                "north_arrow_style": {"placement": "top-left"},
                "legend_style": {"placement": "bottom-right", "title": "Seasons"},
                "static": False,
                "title": None,
                "max_zoom": 20,
            }
            | (params_dict.get("seasonal_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers", "view_state"],
                "argvalues": DependsOn("seasons_view_zip"),
            },
        ),
        "season_etd_ecomap_html_url": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="season_etd_ecomap_html_url")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("season_etd_ecomap_html_url") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("seasonal_ecomap"),
            },
        ),
        "season_etd_widgets_single_view": Node(
            async_task=create_map_widget_single_view.validate()
            .handle_errors(task_instance_id="season_etd_widgets_single_view")
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Subject Group Home Range Map (Seasons)",
            }
            | (params_dict.get("season_etd_widgets_single_view") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("season_etd_ecomap_html_url"),
            },
        ),
        "season_grouped_map_widget": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="season_grouped_map_widget")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("season_etd_widgets_single_view"),
            }
            | (params_dict.get("season_grouped_map_widget") or {}),
            method="call",
        ),
        "determine_subject_season_win": Node(
            async_task=determine_season_windows.validate()
            .handle_errors(task_instance_id="determine_subject_season_win")
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_client"),
                "time_range": DependsOn("define_time_range"),
            }
            | (params_dict.get("determine_subject_season_win") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["roi"],
                "argvalues": DependsOn("generate_etd"),
            },
        ),
        "persist_subject_season_wins": Node(
            async_task=persist_df.validate()
            .handle_errors(task_instance_id="persist_subject_season_wins")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_subject_season_wins") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("determine_subject_season_win"),
            },
        ),
        "zip_nsd_values": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="zip_nsd_values")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("split_relocs_by_group"),
                "right": DependsOn("persist_subject_season_wins"),
            }
            | (params_dict.get("zip_nsd_values") or {}),
            method="call",
        ),
        "generate_nsd_plot": Node(
            async_task=generate_seasonal_nsd_plot.validate()
            .handle_errors(task_instance_id="generate_nsd_plot")
            .set_executor("lithops"),
            partial=(params_dict.get("generate_nsd_plot") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf", "seasons_df"],
                "argvalues": DependsOn("zip_nsd_values"),
            },
        ),
        "persist_seasonal_nsd_plots": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_seasonal_nsd_plots")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_seasonal_nsd_plots") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("generate_nsd_plot"),
            },
        ),
        "zip_speed_values": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="zip_speed_values")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("split_relocs_by_group"),
                "right": DependsOn("persist_subject_season_wins"),
            }
            | (params_dict.get("zip_speed_values") or {}),
            method="call",
        ),
        "generate_speed_plot": Node(
            async_task=generate_seasonal_speed_plot.validate()
            .handle_errors(task_instance_id="generate_speed_plot")
            .set_executor("lithops"),
            partial=(params_dict.get("generate_speed_plot") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf", "seasons_df"],
                "argvalues": DependsOn("zip_speed_values"),
            },
        ),
        "persist_seasonal_speed_plots": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_seasonal_speed_plots")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_seasonal_speed_plots") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("generate_speed_plot"),
            },
        ),
        "zip_mcp_asymp_values": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="zip_mcp_asymp_values")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("split_relocs_by_group"),
                "right": DependsOn("persist_subject_season_wins"),
            }
            | (params_dict.get("zip_mcp_asymp_values") or {}),
            method="call",
        ),
        "generate_mcp_asymp_plot": Node(
            async_task=generate_seasonal_mcp_asymptote_plot.validate()
            .handle_errors(task_instance_id="generate_mcp_asymp_plot")
            .set_executor("lithops"),
            partial=(params_dict.get("generate_mcp_asymp_plot") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf", "seasons_df"],
                "argvalues": DependsOn("zip_mcp_asymp_values"),
            },
        ),
        "persist_mcp_asymp_plots": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="persist_mcp_asymp_plots")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_mcp_asymp_plots") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("generate_mcp_asymp_plot"),
            },
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
