# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_ext_big_life.tasks import aggregate_by as aggregate_by
from ecoscope_workflows_ext_big_life.tasks import crosstab_summary as crosstab_summary
from ecoscope_workflows_ext_big_life.tasks import (
    draw_custom_multi_bar_time_series as draw_custom_multi_bar_time_series,
)
from ecoscope_workflows_ext_big_life.tasks import (
    draw_custom_multi_line_time_series as draw_custom_multi_line_time_series,
)
from ecoscope_workflows_ext_big_life.tasks import (
    generate_density_grid as generate_density_grid,
)
from ecoscope_workflows_ext_big_life.tasks import get_color_map as get_color_map
from ecoscope_workflows_ext_big_life.tasks import (
    map_color_column_value as map_color_column_value,
)
from ecoscope_workflows_ext_big_life.tasks import (
    select_time_frequency as select_time_frequency,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_null_geometry as drop_null_geometry,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    exclude_row_values as exclude_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_pie_chart as draw_pie_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_mep.tasks import custom_map_column as custom_map_column
from ecoscope_workflows_ext_mep.tasks import draw_custom_heatmap as draw_custom_heatmap
from ecoscope_workflows_ext_mep.tasks import (
    herder_effectiveness as herder_effectiveness,
)
from ecoscope_workflows_ext_mep.tasks import (
    load_local_tabular_file as load_local_tabular_file,
)
from ecoscope_workflows_ext_mep.tasks import (
    species_by_ranch_matrix as species_by_ranch_matrix,
)
from ecoscope_workflows_ext_mep.tasks import utm_to_4326 as utm_to_4326
from ecoscope_workflows_ext_mnc.tasks import convert_to_int as convert_to_int
from ecoscope_workflows_ext_mnc.tasks import (
    exclude_geom_outliers as exclude_geom_outliers,
)
from ecoscope_workflows_ext_mnc.tasks import map_column_values as map_column_values
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)
from ecoscope_workflows_ext_ste.tasks import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_custom_text_layer as create_custom_text_layer,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layer_from_gdf as create_deckgl_layer_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks import get_gdf_geom_type as get_gdf_geom_type
from ecoscope_workflows_ext_ste.tasks import view_state_deck_gdf as view_state_deck_gdf
from ecoscope_workflows_ext_ste.tasks import zip_groupbykey as zip_groupbykey

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    time_frequency = (
        select_time_frequency.validate()
        .set_task_instance_id("time_frequency")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("time_frequency") or {}))
        .call()
    )

    configure_base_maps = (
        set_base_maps_pydeck.validate()
        .set_task_instance_id("configure_base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            base_maps=[
                {
                    "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 1,
                    "max_zoom": 20,
                },
                {
                    "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 0.15,
                    "max_zoom": 20,
                },
            ],
            **(params_dict.get("configure_base_maps") or {}),
        )
        .call()
    )

    persist_ambo_gpkg = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("persist_ambo_gpkg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/fcy57d5x5y67gh0xje6rw/lg_group_ranch_boundaries.gpkg?rlkey=yte99xhkte7f1r7n9nemgy7p0&st=sxx1emc1&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("persist_ambo_gpkg") or {}),
        )
        .call()
    )

    persist_hotspot_areas = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("persist_hotspot_areas")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/nlozcti0oqhj6bzvsr46g/lg_conflict_hotspots.gpkg?rlkey=giwdizp1j6e24btgh48uxf5v0&st=jivblame&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("persist_hotspot_areas") or {}),
        )
        .call()
    )

    persist_protected_gpkg = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("persist_protected_gpkg")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/i5yczgyln3zh1n8c4ppl5/lg_protected_areas.gpkg?rlkey=5ea21haq2tmsmx7g502p3qag5&st=zt6ztcku&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params_dict.get("persist_protected_gpkg") or {}),
        )
        .call()
    )

    load_ambo_group_ranches = (
        load_df.validate()
        .set_task_instance_id("load_ambo_group_ranches")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            file_path=persist_ambo_gpkg,
            layer=None,
            deserialize_json=False,
            **(params_dict.get("load_ambo_group_ranches") or {}),
        )
        .call()
    )

    load_hotspot_areas = (
        load_df.validate()
        .set_task_instance_id("load_hotspot_areas")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            file_path=persist_hotspot_areas,
            layer=None,
            deserialize_json=False,
            **(params_dict.get("load_hotspot_areas") or {}),
        )
        .call()
    )

    load_protected_areas = (
        load_df.validate()
        .set_task_instance_id("load_protected_areas")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            file_path=persist_protected_gpkg,
            layer=None,
            deserialize_json=False,
            **(params_dict.get("load_protected_areas") or {}),
        )
        .call()
    )

    reproject_ambo_boundaries = (
        reproject_gdf.validate()
        .set_task_instance_id("reproject_ambo_boundaries")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=load_ambo_group_ranches,
            target_crs="EPSG:4326",
            **(params_dict.get("reproject_ambo_boundaries") or {}),
        )
        .call()
    )

    reproject_hotspot_areas = (
        reproject_gdf.validate()
        .set_task_instance_id("reproject_hotspot_areas")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=load_hotspot_areas,
            target_crs="EPSG:4326",
            **(params_dict.get("reproject_hotspot_areas") or {}),
        )
        .call()
    )

    reproject_protected_areas = (
        reproject_gdf.validate()
        .set_task_instance_id("reproject_protected_areas")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=load_protected_areas,
            target_crs="EPSG:4326",
            **(params_dict.get("reproject_protected_areas") or {}),
        )
        .call()
    )

    annotate_ambo_layers = (
        get_gdf_geom_type.validate()
        .set_task_instance_id("annotate_ambo_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=reproject_ambo_boundaries,
            **(params_dict.get("annotate_ambo_layers") or {}),
        )
        .call()
    )

    annotate_hotspot_layers = (
        get_gdf_geom_type.validate()
        .set_task_instance_id("annotate_hotspot_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=reproject_hotspot_areas,
            **(params_dict.get("annotate_hotspot_layers") or {}),
        )
        .call()
    )

    annotate_protected_layers = (
        get_gdf_geom_type.validate()
        .set_task_instance_id("annotate_protected_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=reproject_protected_areas,
            **(params_dict.get("annotate_protected_layers") or {}),
        )
        .call()
    )

    custom_amboseli_layer = (
        create_deckgl_layer_from_gdf.validate()
        .set_task_instance_id("custom_amboseli_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=annotate_ambo_layers,
            style={
                "get_line_color": [169, 169, 169],
                "get_fill_color": [169, 169, 169],
                "get_line_width": 4.5,
                "opacity": 0.55,
                "extruded": False,
                "stroked": True,
                "filled": False,
            },
            legend={
                "title": "Map layers",
                "values": [{"label": "Group ranch boundaries", "color": "#a9a9a9"}],
            },
            **(params_dict.get("custom_amboseli_layer") or {}),
        )
        .call()
    )

    custom_hotspot_layer = (
        create_deckgl_layer_from_gdf.validate()
        .set_task_instance_id("custom_hotspot_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=annotate_hotspot_layers,
            style={
                "get_line_color": [220, 20, 60],
                "get_fill_color": [220, 20, 60],
                "get_radius": 2.55,
                "get_line_width": 1.95,
                "opacity": 0.75,
                "extruded": False,
                "stroked": True,
                "filled": True,
            },
            legend={
                "title": "",
                "values": [{"label": "Hotspot areas", "color": "#dc143c"}],
            },
            **(params_dict.get("custom_hotspot_layer") or {}),
        )
        .call()
    )

    custom_protected_layer = (
        create_deckgl_layer_from_gdf.validate()
        .set_task_instance_id("custom_protected_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=annotate_protected_layers,
            style={
                "get_line_color": [77, 102, 0],
                "get_fill_color": [77, 102, 0],
                "get_line_width": 1.95,
                "opacity": 0.35,
                "extruded": False,
                "stroked": True,
                "filled": True,
            },
            legend={
                "title": "",
                "values": [
                    {"label": "National parks and reserves", "color": "#4d6600"}
                ],
            },
            **(params_dict.get("custom_protected_layer") or {}),
        )
        .call()
    )

    create_hotspot_text_layer = (
        create_custom_text_layer.validate()
        .set_task_instance_id("create_hotspot_text_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=reproject_hotspot_areas,
            layer_style={
                "get_text": "name",
                "get_color": [20, 20, 20, 255],
                "get_size": 1000,
                "size_units": "meters",
                "size_min_pixels": 40,
                "size_max_pixels": 75,
                "size_scale": 1.25,
                "font_family": "Arial",
                "font_weight": "normal",
                "get_text_anchor": "middle",
                "get_alignment_baseline": "center",
                "billboard": True,
                "background_padding": [4, 8],
                "pickable": True,
                "auto_highlight": False,
            },
            use_centroid=True,
            legend=None,
            **(params_dict.get("create_hotspot_text_layer") or {}),
        )
        .call()
    )

    load_local_lg_file = (
        load_local_tabular_file.validate()
        .set_task_instance_id("load_local_lg_file")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(encoding="latin-1", **(params_dict.get("load_local_lg_file") or {}))
        .call()
    )

    map_predation_columns = (
        map_columns.validate()
        .set_task_instance_id("map_predation_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=load_local_lg_file,
            drop_columns=[
                "Month ",
                "Year",
                "Verified by Biologist",
                "General Comments",
                "Observations",
                "Unknown/ Other",
                "Specific Area",
            ],
            retain_columns=[],
            rename_columns={
                "FID": "id",
                "Date today (MM/DD/YYYY)": "date",
                "Species killed": "species_killed",
                "total killed": "total_killed",
                "Species Injured": "species_injured",
                "total injured": "total_injured",
                "Was the prey livestock (Yes/No)": "is_livestock",
                "Depredation from Boma or Bush?": "boma_or_bush",
                "If bush, were livestock lost? YES/ NO/ NA/ UNKNOWN": "livestock_lost_in_bush",
                "If bush & not lost, were livestock with herder? YES/ NO/ UNKNOWN": "livestock_not_lost_in_bush_herder_present",
                "Group Ranch (MGR, EGR, OGR, Other, Unknown)": "ranch",
                "Community hunt": "community_hunt",
                "Mock hunt": "mock_hunt",
                "Scared by herders- not with spears": "scared_by_herders",
            },
            raise_if_not_found=False,
            **(params_dict.get("map_predation_columns") or {}),
        )
        .call()
    )

    add_temporal_index_to_df = (
        add_temporal_index.validate()
        .set_task_instance_id("add_temporal_index_to_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_predation_columns,
            time_col="date",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("add_temporal_index_to_df") or {}),
        )
        .call()
    )

    replace_values_with_unknown = (
        replace_missing_with_label.validate()
        .set_task_instance_id("replace_values_with_unknown")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_temporal_index_to_df,
            columns=[
                "species_killed",
                "is_livestock",
                "livestock_lost_in_bush",
                "species_injured",
                "livestock_not_lost_in_bush_herder_present",
                "ranch",
                "boma_or_bush",
            ],
            label="Unknown",
            **(params_dict.get("replace_values_with_unknown") or {}),
        )
        .call()
    )

    convert_cols_int = (
        convert_to_int.validate()
        .set_task_instance_id("convert_cols_int")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=replace_values_with_unknown,
            columns=[
                "total_killed",
                "total_injured",
                "community_hunt",
                "mock_hunt",
                "scared_by_herders",
            ],
            errors="coerce",
            fill_value=0,
            inplace=True,
            **(params_dict.get("convert_cols_int") or {}),
        )
        .call()
    )

    map_prey_column = (
        map_column_values.validate()
        .set_task_instance_id("map_prey_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_cols_int,
            columns=["species_killed"],
            value_map={
                "cow": "Cow",
                "bull": "Bull",
                "zebra": "Zebra",
                "Zebra ": "Zebra",
                "shoat": "Shoat",
                "sheep": "Sheep",
                "goat": "Goat",
                "giraffe": "Giraffe",
                "Wildebeest ": "Wildebeest",
                "Cow (calf)": "Cow",
                "Bull": "Cow",
                "Giraffe (foal)": "Giraffe",
                "Zebra (foal)": "Zebra",
                "Eland (calf)": "Eland",
                "Wildebeest (calf)": "Wildebeest",
                "Donkey (foal)": "Donkey",
            },
            inplace=True,
            **(params_dict.get("map_prey_column") or {}),
        )
        .call()
    )

    map_prey_column_value = (
        map_column_values.validate()
        .set_task_instance_id("map_prey_column_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_prey_column,
            columns=["species_injured"],
            inplace=True,
            value_map={
                "cow": "Cow",
                "shoat": "Shoat",
                "donkey": "Donkey",
                "Sheep-kid": "Sheep",
                "Cow (calf)": "Cow",
            },
            **(params_dict.get("map_prey_column_value") or {}),
        )
        .call()
    )

    map_prey_consumed = (
        map_column_values.validate()
        .set_task_instance_id("map_prey_consumed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_prey_column_value,
            columns=["is_livestock"],
            inplace=True,
            value_map={
                "YES": "Yes",
                "NO": "No",
                "Yes": "Yes",
                "No": "No",
                "No prey, but lion disciplined": "No",
            },
            **(params_dict.get("map_prey_consumed") or {}),
        )
        .call()
    )

    map_boma_values = (
        map_column_values.validate()
        .set_task_instance_id("map_boma_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_prey_consumed,
            columns=["boma_or_bush"],
            inplace=True,
            value_map={
                "bush": "Bush",
                "Unknown": "Unknown",
                "BOMA": "Boma",
                "Bush": "Bush",
            },
            **(params_dict.get("map_boma_values") or {}),
        )
        .call()
    )

    map_livestock_columns = (
        map_column_values.validate()
        .set_task_instance_id("map_livestock_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_boma_values,
            columns=[
                "livestock_lost_in_bush",
                "livestock_not_lost_in_bush_herder_present",
            ],
            inplace=True,
            value_map={
                "yes": "Yes",
                "Unknown": "Unknown",
                "Yes": "Yes",
                "unknown": "Unknown",
                "No": "No",
                "NO": "No",
                "no": "No",
                "YES": "Yes",
                "UNKNOWN": "Unknown",
            },
            **(params_dict.get("map_livestock_columns") or {}),
        )
        .call()
    )

    map_ranch_column = (
        map_column_values.validate()
        .set_task_instance_id("map_ranch_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_livestock_columns,
            columns=["ranch"],
            inplace=True,
            value_map={
                "EGR": "EGR",
                "MGR": "MGR",
                "OGR": "OGR",
                "Other-OGR": "OGR",
                "KUKU": "Kuku",
                "Other-KUKU": "Kuku",
                "Other KUKU": "Kuku",
                "Other- Kuku": "Kuku",
                "Other - Kuku GR": "Kuku",
                "Kuku Group ranch": "Kuku",
                "Other - Kaputei": "Kaputei",
                "Other-Kaputei": "Kaputei",
                "Other - Matapato": "Matapato",
                "Other-Matopato": "Matapato",
                "Other - Osilalei Group Ranch": "Osilalei",
                "Other-Kimana": "Kimana",
                "Tanzania": "Tanzania",
                "Other - TZ": "Tanzania",
                "Other-Kunchu": "Other",
                "Other": "Other",
                "Unknown": "Unknown",
                "unknown": "Unknown",
                "UNKNOWN": "Unknown",
            },
            **(params_dict.get("map_ranch_column") or {}),
        )
        .call()
    )

    convert_df_gdf = (
        utm_to_4326.validate()
        .set_task_instance_id("convert_df_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_ranch_column,
            utm_epsg=32737,
            x_col="GPS X (UTM)",
            y_col="GPS Y (UTM)",
            **(params_dict.get("convert_df_gdf") or {}),
        )
        .call()
    )

    map_gdf_columns = (
        map_columns.validate()
        .set_task_instance_id("map_gdf_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_df_gdf,
            drop_columns=["GPS X (UTM)", "GPS Y (UTM)", "None"],
            retain_columns=[],
            rename_columns={},
            raise_if_not_found=False,
            **(params_dict.get("map_gdf_columns") or {}),
        )
        .call()
    )

    map_is_livestock_cols = (
        custom_map_column.validate()
        .set_task_instance_id("map_is_livestock_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_gdf_columns,
            column="is_livestock",
            inplace_col=True,
            mapping={
                "YES": True,
                "Yes": True,
                "yes": True,
                "NO": False,
                "No": False,
                "no": False,
                "No prey, but lion disciplined": False,
            },
            **(params_dict.get("map_is_livestock_cols") or {}),
        )
        .call()
    )

    filter_livestock_gdf = (
        filter_row_values.validate()
        .set_task_instance_id("filter_livestock_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_is_livestock_cols,
            column="species_killed",
            values=["Cow", "Goat", "Shoat", "Donkey", "Sheep", "Bull", "Dog"],
            **(params_dict.get("filter_livestock_gdf") or {}),
        )
        .call()
    )

    exclude_wild_species = (
        exclude_row_values.validate()
        .set_task_instance_id("exclude_wild_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_livestock_gdf,
            column="species_killed",
            values=[
                "Zebra",
                "Wildebeest",
                "Eland",
                "Giraffe",
                "Hyena - spotted",
                "Oryx",
                "Ostrich",
                "Porcupine",
                "Thompson's Gazelle",
                "Grant's Gazelle",
                "Lesser kudu",
                "Buffalo",
                "Gazelle",
            ],
            **(params_dict.get("exclude_wild_species") or {}),
        )
        .call()
    )

    get_species_colors = (
        get_color_map.validate()
        .set_task_instance_id("get_species_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=exclude_wild_species,
            col="species_killed",
            color_dict={
                "Cow": "#fcb5ac",
                "Bull": "#b8d4e8",
                "Goat": "#d4cfe6",
                "Shoat": "#cfc7bd",
                "Sheep": "#fff5b1",
                "Donkey": "#e8c9a8",
                "Dog": "#c2d8c5",
                "Zebra": "#f49990",
                "Wildebeest": "#bcd9de",
                "Buffalo": "#9cbac8",
                "Eland": "#d4edbc",
                "Giraffe": "#e4ecb5",
                "Oryx": "#c9e6d1",
                "Lesser kudu": "#ddc4ae",
                "Gazelle": "#ffd3a5",
                "Thompson's Gazelle": "#d8b8d7",
                "Grant's Gazelle": "#dec4de",
                "Ostrich": "#a8e0d0",
                "Porcupine": "#ffe0b8",
                "Hyena - spotted": "#cfc7bd",
                "Unknown": "#e0e0dc",
            },
            **(params_dict.get("get_species_colors") or {}),
        )
        .call()
    )

    get_boma_or_bush_colors = (
        get_color_map.validate()
        .set_task_instance_id("get_boma_or_bush_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=exclude_wild_species,
            col="boma_or_bush",
            color_dict={"Boma": "#a8d0e6", "Bush": "#c8e6c9", "Unknown": "#e0e0dc"},
            **(params_dict.get("get_boma_or_bush_colors") or {}),
        )
        .call()
    )

    map_ranch_colors = (
        get_color_map.validate()
        .set_task_instance_id("map_ranch_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=exclude_wild_species,
            col="ranch",
            color_dict={
                "EGR": "#fcb5ac",
                "MGR": "#ffd3a5",
                "OGR": "#fff5b1",
                "Kuku": "#d4edbc",
                "Kimana": "#a8e0d0",
                "Kaputei": "#b8d4e8",
                "Matapato": "#d4cfe6",
                "Osilalei": "#e0c4de",
                "Tanzania": "#c4b7dc",
                "Other": "#cfc7bd",
                "Unknown": "#e0e0dc",
            },
            **(params_dict.get("map_ranch_colors") or {}),
        )
        .call()
    )

    map_color_ranch = (
        map_color_column_value.validate()
        .set_task_instance_id("map_color_ranch")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=exclude_wild_species,
            col="ranch",
            mapping={
                "EGR": "#fcb5ac",
                "MGR": "#ffd3a5",
                "OGR": "#fff5b1",
                "Kuku": "#d4edbc",
                "Kimana": "#a8e0d0",
                "Kaputei": "#b8d4e8",
                "Matapato": "#d4cfe6",
                "Osilalei": "#e0c4de",
                "Tanzania": "#c4b7dc",
                "Other": "#cfc7bd",
                "Unknown": "#e0e0dc",
            },
            new_col="ranch_colors",
            **(params_dict.get("map_color_ranch") or {}),
        )
        .call()
    )

    map_color_boma_or_bush = (
        map_color_column_value.validate()
        .set_task_instance_id("map_color_boma_or_bush")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_color_ranch,
            col="boma_or_bush",
            mapping={"Boma": "#a8d0e6", "Bush": "#c8e6c9", "Unknown": "#e0e0dc"},
            new_col="boma_or_bush_colors",
            **(params_dict.get("map_color_boma_or_bush") or {}),
        )
        .call()
    )

    map_color_species_killed = (
        map_color_column_value.validate()
        .set_task_instance_id("map_color_species_killed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_color_boma_or_bush,
            col="species_killed",
            mapping={
                "Cow": "#fcb5ac",
                "Bull": "#b8d4e8",
                "Goat": "#d4cfe6",
                "Shoat": "#cfc7bd",
                "Sheep": "#fff5b1",
                "Donkey": "#e8c9a8",
                "Dog": "#c2d8c5",
                "Zebra": "#f49990",
                "Wildebeest": "#bcd9de",
                "Buffalo": "#9cbac8",
                "Eland": "#d4edbc",
                "Giraffe": "#e4ecb5",
                "Oryx": "#c9e6d1",
                "Lesser kudu": "#ddc4ae",
                "Gazelle": "#ffd3a5",
                "Thompson's Gazelle": "#d8b8d7",
                "Grant's Gazelle": "#dec4de",
                "Ostrich": "#a8e0d0",
                "Porcupine": "#ffe0b8",
                "Hyena - spotted": "#cfc7bd",
                "Unknown": "#e0e0dc",
            },
            new_col="species_killed_colors",
            **(params_dict.get("map_color_species_killed") or {}),
        )
        .call()
    )

    split_events_by_group = (
        split_groups.validate()
        .set_task_instance_id("split_events_by_group")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_color_species_killed,
            groupers=groupers,
            **(params_dict.get("split_events_by_group") or {}),
        )
        .call()
    )

    total_livestock_killed_ranch = (
        crosstab_summary.validate()
        .set_task_instance_id("total_livestock_killed_ranch")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            index_col="species_killed",
            column_col="ranch",
            value_col="total_killed",
            aggfunc="sum",
            reset_index=True,
            margins=True,
            margins_name="Total",
            **(params_dict.get("total_livestock_killed_ranch") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=split_events_by_group)
    )

    persist_total_livestock_killed = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_total_livestock_killed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_prefix="total_livestock_killed_by_ranch",
            filetypes=["csv"],
            sanitize=False,
            **(params_dict.get("persist_total_livestock_killed") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=total_livestock_killed_ranch)
    )

    location_of_attack = (
        aggregate_by.validate()
        .set_task_instance_id("location_of_attack")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col="boma_or_bush",
            agg_func="count",
            agg_col_name="Count",
            agg_col=None,
            sort="asc",
            add_percent=True,
            **(params_dict.get("location_of_attack") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    persist_agg_location = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_agg_location")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_prefix="location_of_attack",
            filetypes=["csv"],
            sanitize=False,
            **(params_dict.get("persist_agg_location") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=location_of_attack)
    )

    herder_location_effectiveness = (
        herder_effectiveness.validate()
        .set_task_instance_id("herder_location_effectiveness")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("herder_location_effectiveness") or {}))
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    persist_herder_effectiveness = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_herder_effectiveness")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_prefix="herder_effectiveness",
            filetypes=["csv"],
            sanitize=False,
            **(params_dict.get("persist_herder_effectiveness") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=herder_location_effectiveness)
    )

    livestock_species_ranch_matrix = (
        species_by_ranch_matrix.validate()
        .set_task_instance_id("livestock_species_ranch_matrix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            livestock_only=True,
            normalize=False,
            **(params_dict.get("livestock_species_ranch_matrix") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    persist_species_matrix = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_species_matrix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_prefix="species_ranch_matrix",
            filetypes=["csv"],
            sanitize=False,
            **(params_dict.get("persist_species_matrix") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=livestock_species_ranch_matrix)
    )

    total_livestock_pie_chart = (
        draw_pie_chart.validate()
        .set_task_instance_id("total_livestock_pie_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value_column="total_killed",
            label_column="species_killed",
            color_column="species_killed_colors",
            plot_style={"textinfo": "percent+label+value"},
            layout_style={"font_size": 15, "font_style": "normal", "showlegend": True},
            **(params_dict.get("total_livestock_pie_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_events_by_group)
    )

    persist_total_livestock_pie = (
        persist_text.validate()
        .set_task_instance_id("persist_total_livestock_pie")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="livestock_killed_pie_chart",
            **(params_dict.get("persist_total_livestock_pie") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=total_livestock_pie_chart)
    )

    ranch_pie_chart = (
        draw_pie_chart.validate()
        .set_task_instance_id("ranch_pie_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value_column="total_killed",
            label_column="ranch",
            color_column="ranch_colors",
            plot_style={"textinfo": "percent+label+value"},
            layout_style={"font_size": 15, "font_style": "normal", "showlegend": True},
            **(params_dict.get("ranch_pie_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_events_by_group)
    )

    persist_ranch_livestock_pie = (
        persist_text.validate()
        .set_task_instance_id("persist_ranch_livestock_pie")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="livestock_killed_by_ranch_pie_chart",
            **(params_dict.get("persist_ranch_livestock_pie") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ranch_pie_chart)
    )

    species_heatmap = (
        draw_custom_heatmap.validate()
        .set_task_instance_id("species_heatmap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            x_axis="species_killed",
            y_axis="ranch",
            value_column="total_killed",
            agg_function="sum",
            time_frequency=None,
            time_column=None,
            time_axis="x",
            normalize=False,
            colorscale="YlOrRd",
            show_values=True,
            x_order=None,
            y_order=None,
            value_label=None,
            layout_style=None,
            **(params_dict.get("species_heatmap") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_events_by_group)
    )

    persist_species_ranch_heatmap = (
        persist_text.validate()
        .set_task_instance_id("persist_species_ranch_heatmap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="species_by_ranch_heatmap",
            **(params_dict.get("persist_species_ranch_heatmap") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=species_heatmap)
    )

    species_time_heatmap = (
        draw_custom_heatmap.validate()
        .set_task_instance_id("species_time_heatmap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            x_axis="species_killed",
            y_axis="species_killed",
            value_column="total_killed",
            agg_function="sum",
            time_frequency=time_frequency,
            time_column="date",
            time_axis="x",
            normalize=False,
            colorscale="YlOrRd",
            show_values=True,
            x_order=None,
            y_order=None,
            value_label=None,
            layout_style=None,
            **(params_dict.get("species_time_heatmap") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_events_by_group)
    )

    persist_species_time_heatmap = (
        persist_text.validate()
        .set_task_instance_id("persist_species_time_heatmap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="species_by_time_heatmap",
            **(params_dict.get("persist_species_time_heatmap") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=species_time_heatmap)
    )

    ranch_killed_multibar_chart = (
        draw_custom_multi_bar_time_series.validate()
        .set_task_instance_id("ranch_killed_multibar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            x_axis="date",
            y_axis="total_killed",
            group_column="ranch",
            agg_function="sum",
            time_frequency=time_frequency,
            ncols=2,
            shared_yaxes=False,
            group_order=None,
            row_height=400,
            ascending=True,
            bar_color="#6495ed",
            x_axis_style={"title": "Date"},
            y_axis_style={"title": "Total animals killed"},
            tick_font_size=None,
            plot_style=None,
            layout_style=None,
            **(params_dict.get("ranch_killed_multibar_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_events_by_group)
    )

    persist_ranch_killed_multibar = (
        persist_text.validate()
        .set_task_instance_id("persist_ranch_killed_multibar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="livestock_species_killed_ranch_multibar",
            **(params_dict.get("persist_ranch_killed_multibar") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ranch_killed_multibar_chart)
    )

    species_killed_multibar_chart = (
        draw_custom_multi_bar_time_series.validate()
        .set_task_instance_id("species_killed_multibar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            x_axis="date",
            y_axis="total_killed",
            group_column="species_killed",
            agg_function="sum",
            time_frequency=time_frequency,
            ncols=2,
            shared_yaxes=False,
            group_order=None,
            row_height=400,
            ascending=True,
            bar_color="#6495ed",
            x_axis_style={"title": "Date"},
            y_axis_style={"title": "Total animals killed"},
            tick_font_size=None,
            plot_style=None,
            layout_style=None,
            **(params_dict.get("species_killed_multibar_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_events_by_group)
    )

    persist_species_killed_multibar = (
        persist_text.validate()
        .set_task_instance_id("persist_species_killed_multibar")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="livestock_species_killed_multibar",
            **(params_dict.get("persist_species_killed_multibar") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=species_killed_multibar_chart)
    )

    ranch_killed_multiline_chart = (
        draw_custom_multi_line_time_series.validate()
        .set_task_instance_id("ranch_killed_multiline_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            x_axis="date",
            y_axis="total_killed",
            group_column="ranch",
            agg_function="sum",
            color_column="ranch_colors",
            line_style={"shape": "linear", "dash": "solid"},
            fill=False,
            ascending=True,
            plot_style=None,
            group_order=None,
            time_frequency=time_frequency,
            layout_style={
                "font_size": 15,
                "legend_title": "Ranch",
                "font_style": "normal",
                "font_color": "#222222",
                "showlegend": True,
                "hovermode": "x unified",
                "plot_bgcolor": "#f5f5f5",
                "title_x": 0.5,
                "xaxis": {
                    "title": "Date",
                    "tickangle": 45,
                    "showgrid": True,
                    "gridcolor": "#e5e5e5",
                },
                "yaxis": {
                    "title": "Number of livestock killed",
                    "showgrid": True,
                    "gridcolor": "#e5e5e5",
                },
            },
            **(params_dict.get("ranch_killed_multiline_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_events_by_group)
    )

    persist_ranch_killed_multiline = (
        persist_text.validate()
        .set_task_instance_id("persist_ranch_killed_multiline")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="livestock_killed_over_time_by_ranch_chart",
            **(params_dict.get("persist_ranch_killed_multiline") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ranch_killed_multiline_chart)
    )

    species_killed_multiline_chart = (
        draw_custom_multi_line_time_series.validate()
        .set_task_instance_id("species_killed_multiline_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            x_axis="date",
            y_axis="total_killed",
            group_column="species_killed",
            agg_function="sum",
            color_column="species_killed_colors",
            line_style={"shape": "linear", "dash": "solid"},
            fill=False,
            ascending=True,
            plot_style=None,
            group_order=None,
            time_frequency=time_frequency,
            layout_style={
                "font_size": 15,
                "legend_title": "Species",
                "font_style": "normal",
                "font_color": "#222222",
                "showlegend": True,
                "hovermode": "x unified",
                "plot_bgcolor": "#f5f5f5",
                "title_x": 0.5,
                "xaxis": {
                    "title": "Date",
                    "tickangle": 45,
                    "showgrid": True,
                    "gridcolor": "#e5e5e5",
                },
                "yaxis": {
                    "title": "Number of livestock killed",
                    "showgrid": True,
                    "gridcolor": "#e5e5e5",
                },
            },
            **(params_dict.get("species_killed_multiline_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_events_by_group)
    )

    persist_species_killed_multiline = (
        persist_text.validate()
        .set_task_instance_id("persist_species_killed_multiline")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="livestock_killed_over_time_by_species_chart",
            **(params_dict.get("persist_species_killed_multiline") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=species_killed_multiline_chart)
    )

    exclude_event_outliers = (
        exclude_geom_outliers.validate()
        .set_task_instance_id("exclude_event_outliers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(z_threshold=3, **(params_dict.get("exclude_event_outliers") or {}))
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    remove_invalid_geoms = (
        drop_null_geometry.validate()
        .set_task_instance_id("remove_invalid_geoms")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geometry_column="geometry",
            **(params_dict.get("remove_invalid_geoms") or {}),
        )
        .mapvalues(argnames=["gdf"], argvalues=exclude_event_outliers)
    )

    generate_livestock_layer = (
        create_scatterplot_layer.validate()
        .set_task_instance_id("generate_livestock_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "get_fill_color": "species_killed_colors",
                "get_line_color": "species_killed_colors",
                "get_radius": 4,
                "opacity": 0.75,
                "stroked": True,
            },
            legend={
                "title": "Livestock species",
                "label_column": "species_killed",
                "color_column": "species_killed_colors",
                "sort": "ascending",
                "label_suffix": None,
            },
            **(params_dict.get("generate_livestock_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=remove_invalid_geoms)
    )

    combine_ambo_lvs_layers = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_ambo_lvs_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[custom_amboseli_layer, custom_protected_layer],
            **(params_dict.get("combine_ambo_lvs_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=generate_livestock_layer)
    )

    global_zoom_value = (
        view_state_deck_gdf.validate()
        .set_task_instance_id("global_zoom_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0,
            bearing=0,
            gdf=reproject_ambo_boundaries,
            **(params_dict.get("global_zoom_value") or {}),
        )
        .call()
    )

    zip_predation_with_viewstate = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_predation_with_viewstate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[combine_ambo_lvs_layers, global_zoom_value],
            **(params_dict.get("zip_predation_with_viewstate") or {}),
        )
        .call()
    )

    draw_livestock_map = (
        draw_map.validate()
        .set_task_instance_id("draw_livestock_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            **(params_dict.get("draw_livestock_map") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"],
            argvalues=zip_predation_with_viewstate,
        )
    )

    persist_livestock_html = (
        persist_text.validate()
        .set_task_instance_id("persist_livestock_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="livestock_predation_map",
            **(params_dict.get("persist_livestock_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_livestock_map)
    )

    generate_predation_grids = (
        generate_density_grid.validate()
        .set_task_instance_id("generate_predation_grids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            cell_size_meters=2000,
            geometry_type="point",
            **(params_dict.get("generate_predation_grids") or {}),
        )
        .mapvalues(argnames=["features_gdf"], argvalues=remove_invalid_geoms)
    )

    sort_density_grid = (
        sort_values.validate()
        .set_task_instance_id("sort_density_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="density",
            ascending=True,
            na_position="last",
            **(params_dict.get("sort_density_grid") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=generate_predation_grids)
    )

    density_bins = (
        apply_classification.validate()
        .set_task_instance_id("density_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density",
            output_column_name="density_bins",
            label_options={"label_ranges": True, "label_decimals": 0},
            classification_options={"scheme": "equal_interval", "k": 5},
            **(params_dict.get("density_bins") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sort_density_grid)
    )

    apply_density_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("apply_density_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            output_column_name="density_bins_colors",
            colormap=["#FFF7BC", "#FD8D3C", "#F03B20", "#BD0026", "#99000D"],
            **(params_dict.get("apply_density_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=density_bins)
    )

    generate_density_layers = (
        create_geojson_layer.validate()
        .set_task_instance_id("generate_density_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "filled": True,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": "density_bins_colors",
                "get_line_color": [0, 0, 0, 200],
                "opacity": 0.55,
                "get_line_width": 0.35,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "Density",
                "label_column": "density_bins",
                "color_column": "density_bins_colors",
                "sort": None,
                "label_suffix": None,
            },
            **(params_dict.get("generate_density_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=apply_density_colormap)
    )

    combine_ambo_grid_layers = (
        combine_deckgl_map_layers.validate()
        .set_task_instance_id("combine_ambo_grid_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=[custom_amboseli_layer, custom_protected_layer],
            **(params_dict.get("combine_ambo_grid_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=generate_density_layers)
    )

    zip_grid_with_viewstate = (
        zip_groupbykey.validate()
        .set_task_instance_id("zip_grid_with_viewstate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sequences=[combine_ambo_grid_layers, global_zoom_value],
            **(params_dict.get("zip_grid_with_viewstate") or {}),
        )
        .call()
    )

    draw_grid_map = (
        draw_map.validate()
        .set_task_instance_id("draw_grid_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            **(params_dict.get("draw_grid_map") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"], argvalues=zip_grid_with_viewstate
        )
    )

    persist_grid_html = (
        persist_text.validate()
        .set_task_instance_id("persist_grid_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="density_grid_map",
            **(params_dict.get("persist_grid_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_grid_map)
    )

    create_predation_widgets = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("create_predation_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Predation points",
            **(params_dict.get("create_predation_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_livestock_html)
    )

    merge_predation_map_widgets = (
        merge_widget_views.validate()
        .set_task_instance_id("merge_predation_map_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=create_predation_widgets,
            **(params_dict.get("merge_predation_map_widgets") or {}),
        )
        .call()
    )

    create_density_widgets = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("create_density_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Predation Density",
            **(params_dict.get("create_density_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_grid_html)
    )

    merge_density_map_widgets = (
        merge_widget_views.validate()
        .set_task_instance_id("merge_density_map_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=create_density_widgets,
            **(params_dict.get("merge_density_map_widgets") or {}),
        )
        .call()
    )

    total_livestock_pie_chart_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("total_livestock_pie_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total livestock killed by species",
            **(params_dict.get("total_livestock_pie_chart_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_total_livestock_pie)
    )

    grouped_killed_pie_widget_merge = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_killed_pie_widget_merge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_livestock_pie_chart_widget,
            **(params_dict.get("grouped_killed_pie_widget_merge") or {}),
        )
        .call()
    )

    ranch_pie_chart_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("ranch_pie_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total livestock killed by ranch",
            **(params_dict.get("ranch_pie_chart_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_ranch_livestock_pie)
    )

    grouped_ranch_pie_widget_merge = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_ranch_pie_widget_merge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=ranch_pie_chart_widget,
            **(params_dict.get("grouped_ranch_pie_widget_merge") or {}),
        )
        .call()
    )

    species_heatmap_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("species_heatmap_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Livestock species killed by ranch",
            **(params_dict.get("species_heatmap_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_species_ranch_heatmap)
    )

    species_heat_widget_merge = (
        merge_widget_views.validate()
        .set_task_instance_id("species_heat_widget_merge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=species_heatmap_widget,
            **(params_dict.get("species_heat_widget_merge") or {}),
        )
        .call()
    )

    time_heatmap_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("time_heatmap_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Livestock species killed by time",
            **(params_dict.get("time_heatmap_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_species_time_heatmap)
    )

    grouped_time_heat_widget_merge = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_time_heat_widget_merge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=time_heatmap_widget,
            **(params_dict.get("grouped_time_heat_widget_merge") or {}),
        )
        .call()
    )

    ranch_line_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("ranch_line_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Livestock species killed by ranch",
            **(params_dict.get("ranch_line_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_ranch_killed_multiline)
    )

    grouped_ranch_line_widget_merge = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_ranch_line_widget_merge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=ranch_line_widget,
            **(params_dict.get("grouped_ranch_line_widget_merge") or {}),
        )
        .call()
    )

    species_line_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("species_line_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Livestock species killed by species",
            **(params_dict.get("species_line_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_species_killed_multiline)
    )

    species_line_widget_merge = (
        merge_widget_views.validate()
        .set_task_instance_id("species_line_widget_merge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=species_line_widget,
            **(params_dict.get("species_line_widget_merge") or {}),
        )
        .call()
    )

    convert_livestock_pie_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_livestock_pie_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_livestock_pie_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_total_livestock_pie)
    )

    convert_ranch_pie_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_ranch_pie_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_ranch_pie_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ranch_livestock_pie)
    )

    convert_species_heat_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_species_heat_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_species_heat_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_species_ranch_heatmap)
    )

    convert_species_time_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_species_time_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_species_time_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_species_time_heatmap)
    )

    convert_ranch_multi_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_ranch_multi_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 2000,
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_ranch_multi_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ranch_killed_multibar)
    )

    convert_species_multi_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_species_multi_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "width": 1280,
                "height": 2000,
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_species_multi_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_species_killed_multibar)
    )

    convert_ranch_line_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_ranch_line_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_ranch_line_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ranch_killed_multiline)
    )

    convert_species_line_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_species_line_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 10,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_species_line_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_species_killed_multiline)
    )

    convert_livestock_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_livestock_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_livestock_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_livestock_html)
    )

    convert_grid_png = (
        html_to_png.validate()
        .set_task_instance_id("convert_grid_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("convert_grid_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_grid_html)
    )

    mep_monthly_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("mep_monthly_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                merge_predation_map_widgets,
                merge_density_map_widgets,
                grouped_killed_pie_widget_merge,
                grouped_ranch_pie_widget_merge,
                species_heat_widget_merge,
                grouped_time_heat_widget_merge,
                grouped_ranch_line_widget_merge,
                species_line_widget_merge,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("mep_monthly_dashboard") or {}),
        )
        .call()
    )

    return mep_monthly_dashboard
