# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class LoadLocalLgFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file_path: str = Field(
        ..., description="Path to the tabular file (CSV or Parquet).", title="File Path"
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalGrouper(BaseModel):
    temporal_index: str = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class TimeFrequency(str, Enum):
    Year = "Year"
    Quarter = "Quarter"
    Month = "Month"
    Week = "Week"
    Day = "Day"
    Hour = "Hour"
    Minute = "Minute"


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper, SpatialGrouper]]] = (
        Field(
            None,
            description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
            title=" ",
        )
    )


class TimeFrequencyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    time_frequency: TimeFrequency = Field(
        ...,
        description="The time frequency to use across all time-series charts in the workflow.",
        title="Time Frequency",
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: Optional[TimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Define analysis time range",
    )
    groupers: Optional[Groupers] = Field(None, title="Configure grouping strategy")
    time_frequency: Optional[TimeFrequencyModel] = Field(
        None, title="Select time frequency for temporal charts"
    )
    load_local_lg_file: Optional[LoadLocalLgFile] = Field(
        None, title="Load local tabular file"
    )
