[dependencies]
curl = '*'
yq = '*'

[dependencies.ecoscope-workflows-core]
channel = 'https://repo.prefix.dev/ecoscope-workflows/'
version = '0.3.*'

[dependencies.ecoscope-workflows-ext-ecoscope]
channel = 'https://repo.prefix.dev/ecoscope-workflows/'
version = '0.3.*'

[project]
channels = ['https://repo.prefix.dev/ecoscope-workflows/', 'conda-forge']
name = 'speedmap'
platforms = ['linux-64', 'osx-arm64']

[tasks]
[tasks.compile]
cmd = './dev/recompile.sh --install'

[tasks.recompile]
cmd = './dev/recompile.sh --update'

[tasks.curl-invoke]
cmd = './dev/curl-invoke-docker.sh'

[tasks.pytest-cli]
cmd = "./dev/pytest.sh speedmap 'cli' sequential"

[tasks.pytest-snapshot-update]
cmd = "./dev/rmrf-snapshots.sh && ./dev/pytest.sh speedmap 'app' 'sequential' --snapshot-update"
