# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Animate Tracks
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_mep.tasks import (
    compute_view_state_from_gdf as compute_view_state_from_gdf,
)
from ecoscope_workflows_ext_mep.tasks import (
    configure_video_export as configure_video_export,
)
from ecoscope_workflows_ext_mep.tasks import (
    create_elevation_decoder as create_elevation_decoder,
)
from ecoscope_workflows_ext_mep.tasks import (
    create_terrain_layer as create_terrain_layer,
)
from ecoscope_workflows_ext_mep.tasks import (
    create_timeline_animation as create_timeline_animation,
)
from ecoscope_workflows_ext_mep.tasks import create_trips_layer as create_trips_layer
from ecoscope_workflows_ext_mep.tasks import draw_animated_map as draw_animated_map
from ecoscope_workflows_ext_mep.tasks import (
    normalize_timestamps as normalize_timestamps,
)
from ecoscope_workflows_ext_mep.tasks import render_animation as render_animation
from ecoscope_workflows_ext_mep.tasks import trajectory_to_trips as trajectory_to_trips

# %% [markdown]
# ## Set workflow details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Connect to EarthRanger

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Define analysis time range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## Configure grouping strategy

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(groupers=[], **groupers_params)
    .call()
)


# %% [markdown]
# ## Set subject group name

# %%
# parameters

subject_group_var_params = dict(
    var=...,
)

# %%
# call the task


subject_group_var = (
    set_string_var.set_task_instance_id("subject_group_var")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**subject_group_var_params)
    .call()
)


# %% [markdown]
# ## Get subject group observations

# %%
# parameters

subject_observations_params = dict()

# %%
# call the task


subject_observations = (
    get_subjectgroup_observations.set_task_instance_id("subject_observations")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        filter="clean",
        client=er_client_name,
        time_range=time_range,
        subject_group_name=subject_group_var,
        raise_on_empty=False,
        include_details=True,
        include_subjectsource_details=True,
        **subject_observations_params,
    )
    .call()
)


# %% [markdown]
# ## Transform observations to relocations

# %%
# parameters

subject_reloc_params = dict()

# %%
# call the task


subject_reloc = (
    process_relocations.set_task_instance_id("subject_reloc")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        observations=subject_observations,
        relocs_columns=[
            "groupby_col",
            "fixtime",
            "junk_status",
            "geometry",
            "extra__subject__name",
            "extra__subject__hex",
            "extra__subject__sex",
            "extra__created_at",
            "extra__subject__subject_subtype",
            "extra__subjectsource__id",
            "extra__subjectsource__assigned_range",
            "extra__observation_details",
        ],
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **subject_reloc_params,
    )
    .call()
)


# %% [markdown]
# ## Convert relocations to trajectories

# %%
# parameters

convert_to_trajs_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


convert_to_trajs = (
    relocations_to_trajectory.set_task_instance_id("convert_to_trajs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(relocations=subject_reloc, **convert_to_trajs_params)
    .call()
)


# %% [markdown]
# ## Standardize trajectory column names

# %%
# parameters

rename_traj_cols_params = dict()

# %%
# call the task


rename_traj_cols = (
    map_columns.set_task_instance_id("rename_traj_cols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=False,
        df=convert_to_trajs,
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "extra__hex": "hex_color",
            "extra__name": "subject_name",
            "extra__sex": "subject_sex",
            "extra__subject_subtype": "subject_subtype",
            "extra__created_at": "created_at",
        },
        **rename_traj_cols_params,
    )
    .call()
)


# %% [markdown]
# ## Save relocations to GeoParquet

# %%
# parameters

persist_relocs_geoparquet_params = dict()

# %%
# call the task


persist_relocs_geoparquet = (
    persist_df.set_task_instance_id("persist_relocs_geoparquet")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=subject_reloc,
        filetype="geoparquet",
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename="relocations",
        **persist_relocs_geoparquet_params,
    )
    .call()
)


# %% [markdown]
# ## Save trajectories to GeoParquet

# %%
# parameters

persist_trajs_geoparquet_params = dict()

# %%
# call the task


persist_trajs_geoparquet = (
    persist_df.set_task_instance_id("persist_trajs_geoparquet")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rename_traj_cols,
        filetype="geoparquet",
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename="trajectories",
        **persist_trajs_geoparquet_params,
    )
    .call()
)


# %% [markdown]
# ## Configure terrain elevation decoder

# %%
# parameters

terrain_exaggeration_params = dict(
    exaggeration=...,
)

# %%
# call the task


terrain_exaggeration = (
    create_elevation_decoder.set_task_instance_id("terrain_exaggeration")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        r_scaler=256,
        g_scaler=1.0,
        b_scaler=0.00390625,
        offset=-32768.0,
        **terrain_exaggeration_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare trajectory animation data

# %%
# parameters

trajs_trips_params = dict()

# %%
# call the task


trajs_trips = (
    trajectory_to_trips.set_task_instance_id("trajs_trips")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        trajectory_gdf=rename_traj_cols,
        subject_name_col="subject_name",
        subject_hex_col="hex_color",
        terrain={
            "zoom": 15,
            "offset": 30,
            "cache_dir": None,
            "ground_elevation": 1500,
            "elevation_decoder": terrain_exaggeration,
            "elevation_data": "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png",
        },
        **trajs_trips_params,
    )
    .call()
)


# %% [markdown]
# ## Create terrain layer

# %%
# parameters

terrain_layer_params = dict()

# %%
# call the task


terrain_layer = (
    create_terrain_layer.set_task_instance_id("terrain_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        min_zoom=0,
        max_zoom=15,
        elevation_data="https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png",
        texture="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        wireframe=False,
        elevation_decoder=terrain_exaggeration,
        **terrain_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate map view bounds

# %%
# parameters

trips_view_state_params = dict(
    pitch=...,
    bearing=...,
)

# %%
# call the task


trips_view_state = (
    compute_view_state_from_gdf.set_task_instance_id("trips_view_state")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=trajs_trips, **trips_view_state_params)
    .call()
)


# %% [markdown]
# ## Normalize animation timestamps

# %%
# parameters

normalize_trips_params = dict()

# %%
# call the task


normalize_trips = (
    normalize_timestamps.set_task_instance_id("normalize_trips")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(target_span=None, df=trajs_trips, **normalize_trips_params)
    .call()
)


# %% [markdown]
# ## Create trips layer

# %%
# parameters

trips_layer_params = dict()

# %%
# call the task


trips_layer = (
    create_trips_layer.set_task_instance_id("trips_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=normalize_trips,
        data_url=None,
        layer_style={
            "get_timestamps": "timestamps",
            "get_color": "color",
            "get_width": 2.25,
            "width_units": "pixels",
            "width_scale": 1,
            "width_min_pixels": 1,
            "width_max_pixels": 5,
            "cap_rounded": True,
            "joint_rounded": True,
            "billboard": False,
            "fade_trail": True,
            "current_time": 0,
            "trail_length": 120,
        },
        legend={
            "title": "Subjects",
            "label_column": "name",
            "color_column": "color",
            "sort": "ascending",
            "label_suffix": None,
        },
        **trips_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Configure animation settings

# %%
# parameters

animation_settings_params = dict(
    animation_speed=...,
    auto_rotate_speed=...,
)

# %%
# call the task


animation_settings = (
    create_timeline_animation.set_task_instance_id("animation_settings")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        fade_ratio=1.0,
        fps_limit=30,
        show_history=True,
        history_color=[255, 255, 255],
        head_outline_color=[255, 255, 255],
        history_opacity=1.0,
        fade_history=True,
        show_head=True,
        head_radius=1.75,
        head_color=None,
        head_outline_width=1.05,
        **animation_settings_params,
    )
    .call()
)


# %% [markdown]
# ## Draw animated map

# %%
# parameters

draw_animation_params = dict(
    widget_id=...,
    head_layer=...,
)

# %%
# call the task


draw_animation = (
    draw_animated_map.set_task_instance_id("draw_animation")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geo_layers=[trips_layer],
        tile_layers=[terrain_layer],
        static=False,
        max_zoom=15,
        title=None,
        legend_style={"placement": "bottom-right"},
        view_state=trips_view_state,
        animation=animation_settings,
        **draw_animation_params,
    )
    .call()
)


# %% [markdown]
# ## Save animated map as HTML

# %%
# parameters

map_urls_params = dict(
    filename_suffix=...,
)

# %%
# call the task


map_urls = (
    persist_text.set_task_instance_id("map_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_animation,
        filename="animated_map.html",
        **map_urls_params,
    )
    .call()
)


# %% [markdown]
# ## Configure video export

# %%
# parameters

video_output_path_params = dict(
    enabled=...,
)

# %%
# call the task


video_output_path = (
    configure_video_export.set_task_instance_id("video_output_path")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(filename=map_urls, **video_output_path_params)
    .call()
)


# %% [markdown]
# ## Render animation video

# %%
# parameters

create_animation_params = dict(
    camera=...,
    fps=...,
    duration=...,
    width=...,
    height=...,
)

# %%
# call the task


create_animation = (
    render_animation.set_task_instance_id("create_animation")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        html_path=video_output_path,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        out_path="animation.mp4",
        device_scale_factor=1,
        gl="auto",
        workers=1,
        capture_format="jpeg",
        jpeg_quality=92,
        settle_ms=30,
        settle_timeout_ms=8000,
        head_ready_timeout_ms=30000,
        crf=18,
        x264_preset="veryfast",
        subject_index=0,
        zoom=None,
        pitch=None,
        bearing=None,
        follow_smoothing=0.25,
        zoom_boost=0.0,
        heading_lock=False,
        orbits=1.0,
        fit_padding=80,
        lead_frac=0.0,
        bearing_mode="rotate",
        rotate_deg=45.0,
        intro_frac=0.12,
        intro_zoom_out=2.5,
        start_frac=0.0,
        end_frac=1.0,
        verbose=True,
        **create_animation_params,
    )
    .call()
)


# %% [markdown]
# ## Create animated map widget

# %%
# parameters

animated_map_widget_params = dict(
    view=...,
)

# %%
# call the task


animated_map_widget = (
    create_map_widget_single_view.set_task_instance_id("animated_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(title="Subject movements", data=map_urls, **animated_map_widget_params)
    .call()
)


# %% [markdown]
# ## Generate Dashboard

# %%
# parameters

animate_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


animate_dashboard = (
    gather_dashboard.set_task_instance_id("animate_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[animated_map_widget],
        time_range=time_range,
        groupers=groupers,
        **animate_dashboard_params,
    )
    .call()
)
