# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_subjectgroup_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.transformation import convert_crs as convert_crs
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_mep.tasks.animate import animate_layer as animate_layer
from ecoscope_workflows_ext_mep.tasks.animate import (
    create_elevation_decoder as create_elevation_decoder,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    create_playback_controls as create_playback_controls,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    create_terrain_layer as create_terrain_layer,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    create_terrain_sampling as create_terrain_sampling,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    create_timeline_animation as create_timeline_animation,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    create_trips_animation as create_trips_animation,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    create_trips_layer as create_trips_layer,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    drape_trips_on_terrain as drape_trips_on_terrain,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    draw_animated_map as draw_animated_map,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    render_animation as render_animation,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    set_basemap_option as set_basemap_option,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    set_basemap_urls as set_basemap_urls,
)
from ecoscope_workflows_ext_mep.tasks.animate import (
    trajectory_to_trips as trajectory_to_trips,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    compute_view_state_from_gdf as compute_view_state_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    envelope_gdf as envelope_gdf,
)
from ecoscope_workflows_ext_ste.tasks.transformation import (
    add_rgba_from_hex as add_rgba_from_hex,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    subject_observations = (
        task(get_subjectgroup_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("subject_observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filter="clean",
            client=er_client_name,
            time_range=time_range,
            raise_on_empty=False,
            include_details=True,
            include_subjectsource_details=True,
            **(params.get("subject_observations") or {}),
        )
        .call()
    )

    subject_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=subject_observations,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__hex",
                "extra__subject__sex",
                "extra__created_at",
                "extra__subject__subject_subtype",
                "extra__subjectsource__id",
                "extra__subjectsource__assigned_range",
                "extra__observation_details",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("subject_reloc") or {}),
        )
        .call()
    )

    convert_to_trajs = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("convert_to_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=subject_reloc, **(params.get("convert_to_trajs") or {}))
        .call()
    )

    rename_traj_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_traj_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=False,
            df=convert_to_trajs,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__hex": "hex_color",
                "extra__name": "subject_name",
                "extra__sex": "subject_sex",
                "extra__subject_subtype": "subject_subtype",
                "extra__created_at": "created_at",
            },
            **(params.get("rename_traj_cols") or {}),
        )
        .call()
    )

    persist_relocs_geoparquet = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_relocs_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_reloc,
            filetypes=["geoparquet"],
            filename_prefix="relocations",
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            **(params.get("persist_relocs_geoparquet") or {}),
        )
        .call()
    )

    persist_trajs_geoparquet = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_trajs_geoparquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_traj_cols,
            filetypes=["geoparquet"],
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="trajectories",
            sanitize=True,
            **(params.get("persist_trajs_geoparquet") or {}),
        )
        .call()
    )

    terrain_exaggeration = (
        task(create_elevation_decoder)
        .validate()
        .set_task_instance_id("terrain_exaggeration")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            r_scaler=256,
            g_scaler=1.0,
            b_scaler=0.00390625,
            offset=-32768.0,
            **(params.get("terrain_exaggeration") or {}),
        )
        .call()
    )

    custom_basemap_urls = (
        task(set_basemap_urls)
        .validate()
        .set_task_instance_id("custom_basemap_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            elevation_data="https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png",
            texture="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
            **(params.get("custom_basemap_urls") or {}),
        )
        .call()
    )

    basemap_option = (
        task(set_basemap_option)
        .validate()
        .set_task_instance_id("basemap_option")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            basemap={
                "preset": "default",
                "elevation_decoder": terrain_exaggeration,
                "tile_urls": custom_basemap_urls,
            },
            **(params.get("basemap_option") or {}),
        )
        .call()
    )

    ensure_wgs = (
        task(convert_crs)
        .validate()
        .set_task_instance_id("ensure_wgs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_traj_cols, crs="EPSG:4326", **(params.get("ensure_wgs") or {})
        )
        .call()
    )

    trajs_trips = (
        task(trajectory_to_trips)
        .validate()
        .set_task_instance_id("trajs_trips")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trajectory_gdf=ensure_wgs,
            groupby_col="groupby_col",
            keep_cols=["subject_name", "hex_color"],
            **(params.get("trajs_trips") or {}),
        )
        .call()
    )

    terrain_sampling = (
        task(create_terrain_sampling)
        .validate()
        .set_task_instance_id("terrain_sampling")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            elevation_data="https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png",
            elevation_decoder=terrain_exaggeration,
            **(params.get("terrain_sampling") or {}),
        )
        .call()
    )

    drape_terrain = (
        task(drape_trips_on_terrain)
        .validate()
        .set_task_instance_id("drape_terrain")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trips_gdf=trajs_trips,
            terrain=terrain_sampling,
            **(params.get("drape_terrain") or {}),
        )
        .call()
    )

    terrain_layer = (
        task(create_terrain_layer)
        .validate()
        .set_task_instance_id("terrain_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            min_zoom=0,
            max_zoom=15,
            wireframe=False,
            elevation_data="https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png",
            texture="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
            elevation_decoder=terrain_exaggeration,
            **(params.get("terrain_layer") or {}),
        )
        .call()
    )

    zoom_to_envelope = (
        task(envelope_gdf)
        .validate()
        .set_task_instance_id("zoom_to_envelope")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            expansion_factor=1.0,
            gdf=trajs_trips,
            **(params.get("zoom_to_envelope") or {}),
        )
        .call()
    )

    trips_view_state = (
        task(compute_view_state_from_gdf)
        .validate()
        .set_task_instance_id("trips_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            max_zoom=15, gdf=zoom_to_envelope, **(params.get("trips_view_state") or {})
        )
        .call()
    )

    rgba_hex = (
        task(add_rgba_from_hex)
        .validate()
        .set_task_instance_id("rgba_hex")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="hex_color",
            new_column="rgba_color",
            df=drape_terrain,
            **(params.get("rgba_hex") or {}),
        )
        .call()
    )

    trips_animation = (
        task(create_trips_animation)
        .validate()
        .set_task_instance_id("trips_animation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            comet_ratio=0.95,
            show_history=True,
            history_color=[255, 255, 255],
            fade_history=True,
            history_opacity=0.85,
            **(params.get("trips_animation") or {}),
        )
        .call()
    )

    trips_layer = (
        task(create_trips_layer)
        .validate()
        .set_task_instance_id("trips_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=rgba_hex,
            data_url=None,
            layer_style={
                "get_timestamps": "timestamps",
                "get_color": "rgba_color",
                "get_width": 2.15,
                "width_units": "pixels",
                "width_scale": 1,
                "width_min_pixels": 1,
                "width_max_pixels": 4,
                "cap_rounded": True,
                "joint_rounded": True,
                "billboard": False,
                "fade_trail": True,
                "current_time": 0,
                "trail_length": 120,
            },
            legend={
                "title": "Subjects",
                "label_column": "subject_name",
                "color_column": "rgba_color",
                "sort": "ascending",
                "label_suffix": None,
            },
            **(params.get("trips_layer") or {}),
        )
        .call()
    )

    animate_trips = (
        task(animate_layer)
        .validate()
        .set_task_instance_id("animate_trips")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer=trips_layer,
            animation=trips_animation,
            **(params.get("animate_trips") or {}),
        )
        .call()
    )

    create_controls = (
        task(create_playback_controls)
        .validate()
        .set_task_instance_id("create_controls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(speeds=[0.5, 1, 2, 4], **(params.get("create_controls") or {}))
        .call()
    )

    timeline_animation = (
        task(create_timeline_animation)
        .validate()
        .set_task_instance_id("timeline_animation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            fps_limit=30,
            controls=create_controls,
            **(params.get("timeline_animation") or {}),
        )
        .call()
    )

    draw_animation = (
        task(draw_animated_map)
        .validate()
        .set_task_instance_id("draw_animation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=animate_trips,
            tile_layers=[terrain_layer],
            static=False,
            max_zoom=15,
            title=None,
            legend_style={"placement": "bottom-right"},
            view_state=trips_view_state,
            widget_id=None,
            timeline=timeline_animation,
            **(params.get("draw_animation") or {}),
        )
        .call()
    )

    map_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("map_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_animation,
            filename="animated_map.html",
            **(params.get("map_urls") or {}),
        )
        .call()
    )

    create_animation = (
        task(render_animation)
        .validate()
        .set_task_instance_id("create_animation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=map_urls,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            out_path="animation.mp4",
            fps=30,
            start_frac=0,
            end_frac=1,
            verbose=True,
            quality={
                "capture_format": "jpeg",
                "jpeg_quality": 92,
                "crf": 18,
                "x264_preset": "veryfast",
                "device_scale_factor": 1,
            },
            capture={
                "gl": "auto",
                "workers": "auto",
                "settle_ms": 30,
                "settle_timeout_ms": 8000,
                "head_ready_timeout_ms": 30000,
            },
            **(params.get("create_animation") or {}),
        )
        .call()
    )

    animated_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("animated_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Subject movements",
            data=map_urls,
            **(params.get("animated_map_widget") or {}),
        )
        .call()
    )

    animate_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("animate_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[animated_map_widget],
            time_range=time_range,
            groupers=groupers,
            **(params.get("animate_dashboard") or {}),
        )
        .call()
    )

    return animate_dashboard
