name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["310", "311", "312"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.0

      - name: Install Pixi
        run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Run tests (pytest)
        run: |
          pixi run --manifest-path pixi.toml pytest-${{ matrix.python-version }}
